// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d464349017863a9be94937c43f86c9006bdb89e54570c14ebc97b68565d7de63
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
