# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3877ae61d005245b982a1783ed79c5233c45caa84448ab35fc6d1b0fe0c47978
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: async
defmodule E2e.AsyncTest do
  use ExUnit.Case, async: false

  describe "async_extract_bytes_empty_mime" do
    test "async_extract_bytes_empty_mime" do
      content = File.read!("../../test_documents/text/plain.txt")
      assert {:error, _} = Kreuzberg.extract_bytes_async(content, "", "{}")
    end
  end

  describe "async_extract_bytes_invalid_mime" do
    test "async_extract_bytes_invalid_mime" do
      content = File.read!("../../test_documents/text/plain.txt")
      assert {:error, _} = Kreuzberg.extract_bytes_async(content, "application/x-nonexistent", "{}")
    end
  end
end
