# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:996d083e849c3a6f30ff0810a2b40db3cee4c3aa61b104e8fbab72c7fef7b4b0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
"""Exception hierarchy."""


class KreuzbergError(Exception):
    """Main error type for all Kreuzberg operations."""


class IoError(KreuzbergError):
    """Io error."""


class ParsingError(KreuzbergError):
    """Parsing error."""


class OcrError(KreuzbergError):
    """Ocr error."""


class ValidationError(KreuzbergError):
    """Validation error."""


class CacheError(KreuzbergError):
    """Cache error."""


class ImageProcessingError(KreuzbergError):
    """Image processing error."""


class SerializationError(KreuzbergError):
    """Serialization error."""


class MissingDependencyError(KreuzbergError):
    """Missing dependency error."""


class PluginError(KreuzbergError):
    """Plugin error."""


class LockPoisonedError(KreuzbergError):
    """Lock poisoned error."""


class UnsupportedFormatError(KreuzbergError):
    """Unsupported format error."""


class EmbeddingError(KreuzbergError):
    """Embedding error."""


class KreuzbergTimeoutError(KreuzbergError):
    """Kreuzberg timeout error."""


class CancelledError(KreuzbergError):
    """Cancelled error."""


class SecurityError(KreuzbergError):
    """Security error."""


class OtherError(KreuzbergError):
    """Other error."""
