// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:129e047ce1c8f5a8bbc18ca19ed47a0ef5e118d35576956b5290d49c7813326e
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ApiDocSafeHandle : SafeHandle
{
    internal ApiDocSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ApiDocFree(handle);
        return true;
    }
}
/// <summary>/// OpenAPI documentation structure./// /// Defines all endpoints, request/response schemas, and examples/// for the Kreuzberg document extraction API./// </summary>
public sealed class ApiDoc : IDisposable
{
    private readonly ApiDocSafeHandle _safeHandle;

    internal ApiDoc(IntPtr handle)
    {
        _safeHandle = new ApiDocSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
