// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4c89333b09d4f42e9e11caa3b222967d2843f061a8ce9977c72d02ad6eecc36b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Archive (ZIP/TAR/7Z) metadata.
///
/// Extracted from compressed archive files containing file lists and size information.
/// </summary>
public sealed record ArchiveMetadata
{
    /// <summary>
    /// Archive format ("ZIP", "TAR", "7Z", etc.)
    /// </summary>
    [JsonPropertyName("format")]
    public string Format { get; init; } = "";

    /// <summary>
    /// Total number of files in the archive
    /// </summary>
    [JsonPropertyName("file_count")]
    public uint FileCount { get; init; } = 0;

    /// <summary>
    /// List of file paths within the archive
    /// </summary>
    [JsonPropertyName("file_list")]
    public List<string> FileList { get; init; } = [];

    /// <summary>
    /// Total uncompressed size in bytes
    /// </summary>
    [JsonPropertyName("total_size")]
    public ulong TotalSize { get; init; } = 0;

    /// <summary>
    /// Compressed size in bytes (if available)
    /// </summary>
    [JsonPropertyName("compressed_size")]
    public ulong? CompressedSize { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="ArchiveMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ArchiveMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ArchiveMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ArchiveMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ArchiveMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
