// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f8ba606e7e3eba7860f3f28d493136b6e3fb6acc7cb603b51a40f2c36dd5b7e3
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Types of block-level elements in Djot.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum BlockType
{    [JsonPropertyName("paragraph")]
    Paragraph,    [JsonPropertyName("heading")]
    Heading,    [JsonPropertyName("blockquote")]
    Blockquote,    [JsonPropertyName("code_block")]
    CodeBlock,    [JsonPropertyName("list_item")]
    ListItem,    [JsonPropertyName("ordered_list")]
    OrderedList,    [JsonPropertyName("bullet_list")]
    BulletList,    [JsonPropertyName("task_list")]
    TaskList,    [JsonPropertyName("definition_list")]
    DefinitionList,    [JsonPropertyName("definition_term")]
    DefinitionTerm,    [JsonPropertyName("definition_description")]
    DefinitionDescription,    [JsonPropertyName("div")]
    Div,    [JsonPropertyName("section")]
    Section,    [JsonPropertyName("thematic_break")]
    ThematicBreak,    [JsonPropertyName("raw_block")]
    RawBlock,    [JsonPropertyName("math_display")]
    MathDisplay,}
