// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:717cea039bb0eab3fe5bf4397b9234e64bf18a85ff2dbdf1122fcde55246679e
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
