// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8a3f68b8b3eeb3c569041c99794b8ef06885bdb4063de4d917720e8d11ab44b7
#nullable enable

using System;

namespace Kreuzberg;

public class CacheException : KreuzbergErrorException
{
    public CacheException(string message) : base(message) { }

    public CacheException(string message, Exception innerException) : base(message, innerException) { }
}
