// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:e3b69d98c88d5dd3d0e8e65e72918004a92d5852698c9916ce6a5f9660bb4371
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
