// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8d1953e8c2d773975be11777572fe88a58421e78dd6fddd2e14c72abb46ce6d3
#nullable enable

using System;

namespace Kreuzberg;

public class CancelledException : KreuzbergErrorException
{
    public CancelledException(string message) : base(message) { }

    public CancelledException(string message, Exception innerException) : base(message, innerException) { }
}
