// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0775d2950cd4fdcf979d870850c7439ed4f114cb3e41b91b287ade7d516c261e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Content rendering mode for code extraction.
///
/// Controls how extracted code content is represented in the `content` field
/// of `ExtractionResult`.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CodeContentMode
{    /// <summary>
    /// Use TSLP semantic chunks as content (default).
    /// </summary>
    [JsonPropertyName("chunks")]
    Chunks,    /// <summary>
    /// Use raw source code as content.
    /// </summary>
    [JsonPropertyName("raw")]
    Raw,    /// <summary>
    /// Emit function/class headings + docstrings (no code bodies).
    /// </summary>
    [JsonPropertyName("structure")]
    Structure,}
