// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7164a70eda775d401a3072f1f7d43211ad2280f0cc21b35c974d289822b24d59
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Content rendering mode for code extraction./// /// Controls how extracted code content is represented in the `content` field/// of `ExtractionResult`./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum CodeContentMode
{/// <summary>    /// Use TSLP semantic chunks as content (default).    /// </summary>
[JsonPropertyName("chunks")]
    Chunks,/// <summary>    /// Use raw source code as content.    /// </summary>
[JsonPropertyName("raw")]
    Raw,/// <summary>    /// Emit function/class headings + docstrings (no code bodies).    /// </summary>
[JsonPropertyName("structure")]
    Structure,}
