// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a85ea22a67ff23bfc3fc2a97b2a34665cf3b3b1613129ab091722525525a2136
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Content layer classification for document nodes./// /// Replaces separate body/furniture arrays with per-node granularity./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ContentLayer
{/// <summary>    /// Main document body content.    /// </summary>
[JsonPropertyName("body")]
    Body,/// <summary>    /// Page/section header (running header).    /// </summary>
[JsonPropertyName("header")]
    Header,/// <summary>    /// Page/section footer (running footer).    /// </summary>
[JsonPropertyName("footer")]
    Footer,/// <summary>    /// Footnote content.    /// </summary>
[JsonPropertyName("footnote")]
    Footnote,}
