// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22f2fa63502a791d33f1bbf291375cdad018aa10a69d654d7440cc1f21843bf3
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// JATS contributor with role.
/// </summary>
public sealed record ContributorRole
{
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("role")]
    public string? Role { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="ContributorRole"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ContributorRole FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ContributorRole>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ContributorRole from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ContributorRole from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
