// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5dbc6ed65f1b6b6a46ed7ea275257775554263575a3359890b4e93d8439d2cd9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// MIME type detection response.
/// </summary>
public sealed record DetectResponse
{
    /// <summary>
    /// Detected MIME type
    /// </summary>
    [JsonPropertyName("mime_type")]
    public required string MimeType { get; init; }

    /// <summary>
    /// Original filename (if provided)
    /// </summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; init; } = null;


    /// <summary>
    /// Parse a <see cref="DetectResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DetectResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DetectResponse>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DetectResponse from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DetectResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
