// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:aceff5eae276e5c22dace92ceadf1e77bf3567286d19330d7195c1d56e67c90d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OpenWebUI "Docling" engine response format.
///
/// Returned by `POST /v1/convert/file` for docling-serve compatibility.
/// </summary>
public sealed class DoclingCompatResponse
{
    /// <summary>
    /// Converted document content
    /// </summary>
    [JsonPropertyName("document")]
    public string Document { get; set; } = "";

    /// <summary>
    /// Processing status
    /// </summary>
    [JsonPropertyName("status")]
    public string Status { get; set; } = "";


    /// <summary>
    /// Parse a <see cref="DoclingCompatResponse"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static DoclingCompatResponse FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<DoclingCompatResponse>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse DoclingCompatResponse from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse DoclingCompatResponse from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
