// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1d5db467ed3ae793d50209e5578f04ed8174f6c621b3cc2d456e73b074acab5c
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Whether the drawing is inline or anchored.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum DrawingType
{    [JsonPropertyName("inline")]
    Inline,    [JsonPropertyName("anchored")]
    Anchored,}
