// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:498cf7b14f5b5454f2dc0d3403a382110403b9ceb21e801e5322cadc42151ba3
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Semantic element type classification.
///
/// Categorizes text content into semantic units for downstream processing.
/// Supports the element types commonly found in Unstructured documents.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ElementType
{    /// <summary>
    /// Document title
    /// </summary>
    [JsonPropertyName("title")]
    Title,    /// <summary>
    /// Main narrative text body
    /// </summary>
    [JsonPropertyName("narrative_text")]
    NarrativeText,    /// <summary>
    /// Section heading
    /// </summary>
    [JsonPropertyName("heading")]
    Heading,    /// <summary>
    /// List item (bullet, numbered, etc.)
    /// </summary>
    [JsonPropertyName("list_item")]
    ListItem,    /// <summary>
    /// Table element
    /// </summary>
    [JsonPropertyName("table")]
    Table,    /// <summary>
    /// Image element
    /// </summary>
    [JsonPropertyName("image")]
    Image,    /// <summary>
    /// Page break marker
    /// </summary>
    [JsonPropertyName("page_break")]
    PageBreak,    /// <summary>
    /// Code block
    /// </summary>
    [JsonPropertyName("code_block")]
    CodeBlock,    /// <summary>
    /// Block quote
    /// </summary>
    [JsonPropertyName("block_quote")]
    BlockQuote,    /// <summary>
    /// Footer text
    /// </summary>
    [JsonPropertyName("footer")]
    Footer,    /// <summary>
    /// Header text
    /// </summary>
    [JsonPropertyName("header")]
    Header,}
