// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fd755fdaaa5fd8ba42318763c1d109982e56f1a290864cb422a02eb0b62b0dd2
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
