// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0db947308a6af6eaa48c642f533ccc9ac28b1d9f2074e7564379befc61ceb964
#nullable enable

using System;

namespace Kreuzberg;

public class EmbeddingException : KreuzbergErrorException
{
    public EmbeddingException(string message) : base(message) { }

    public EmbeddingException(string message, Exception innerException) : base(message, innerException) { }
}
