// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:29e3821b667c215e2c855297ce1830c59acb633d9d36d42caeeb3c38fa594572
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// OCR extraction result
/// </summary>
public sealed record ExtractionResult2
{
    [JsonPropertyName("content")]
    public required string Content { get; init; }

    [JsonPropertyName("mime_type")]
    public required string MimeType { get; init; }

    [JsonPropertyName("metadata")]
    public Dictionary<string, object> Metadata { get; init; } = default!;

    [JsonPropertyName("tables")]
    public List<Table> Tables { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="ExtractionResult2"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ExtractionResult2 FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExtractionResult2>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ExtractionResult2 from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ExtractionResult2 from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
