// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:207b9f31865565535f6d1a8862b41b48154ec2336b655b6bb389c8a80b7c4d1b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// How the extracted text was produced.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExtractionMethod2
{    [JsonPropertyName("native")]
    Native,    [JsonPropertyName("ocr")]
    Ocr,    [JsonPropertyName("mixed")]
    Mixed,}
