// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:12b6d5940600d66bc314acad904a7ae79dc2acf4d070a5357e0853cbd8484cc9
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// How the extracted text was produced./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ExtractionMethod
{[JsonPropertyName("native")]
    Native,[JsonPropertyName("ocr")]
    Ocr,[JsonPropertyName("mixed")]
    Mixed,}
