// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:71013cc21902354035f678909b897adf40c9d4081429e9c07333f7913a59756d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Image metadata extracted from an image file.
/// </summary>
public sealed record ExtractedImageMetadata
{
    /// <summary>
    /// Image width in pixels
    /// </summary>
    [JsonPropertyName("width")]
    public uint Width { get; init; } = 0;

    /// <summary>
    /// Image height in pixels
    /// </summary>
    [JsonPropertyName("height")]
    public uint Height { get; init; } = 0;

    /// <summary>
    /// Image format (e.g., "PNG", "JPEG")
    /// </summary>
    [JsonPropertyName("format")]
    public required string Format { get; init; }

    /// <summary>
    /// EXIF data if available
    /// </summary>
    [JsonPropertyName("exif_data")]
    public Dictionary<string, string> ExifData { get; init; } = default!;


    /// <summary>
    /// Parse a <see cref="ExtractedImageMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static ExtractedImageMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<ExtractedImageMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse ExtractedImageMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse ExtractedImageMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
