// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:25f91c1f1383b00240f3502022233a897e02d4f36a2e0a6e42774a2e1bc11e08
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FracType
{    [JsonPropertyName("bar")]
    Bar,    [JsonPropertyName("nobar")]
    NoBar,    [JsonPropertyName("linear")]
    Linear,    [JsonPropertyName("skewed")]
    Skewed,}
