// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5c6b3caff13aa0556153bb192733ef89109bfe6814f30ff87790924c89847049
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum FracType
{[JsonPropertyName("bar")]
    Bar,[JsonPropertyName("nobar")]
    NoBar,[JsonPropertyName("linear")]
    Linear,[JsonPropertyName("skewed")]
    Skewed,}
