// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8518b6d2f52f74e1521333f7b477320ec08d6445d5fd9e9f2faf61322b82c60e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Configuration for styled HTML output.
///
/// When set on [`ExtractionConfig::html_output`] alongside
/// `output_format = OutputFormat::Html`, the pipeline builds a
/// [`StyledHtmlRenderer`](crate::rendering::StyledHtmlRenderer) instead of
/// the plain comrak-based renderer.
///
/// # Example
///
/// ```rust
/// use kreuzberg::core::config::{HtmlOutputConfig, HtmlTheme};
///
/// let config = HtmlOutputConfig {
///     theme: HtmlTheme::GitHub,
///     css: Some(".kb-p { font-size: 1.1rem; }".to_string()),
///     ..Default::default()
/// };
/// ```
/// </summary>
public sealed record HTMLOutputConfig
{
    /// <summary>
    /// Inline CSS string injected into the output after the theme stylesheet.
    /// Concatenated after `css_file` content when both are set.
    /// </summary>
    [JsonPropertyName("css")]
    public string? CSS { get; init; } = null;

    /// <summary>
    /// Path to a CSS file loaded once at renderer construction time.
    /// Concatenated before `css` when both are set.
    /// </summary>
    [JsonPropertyName("css_file")]
    public string? CSSFile { get; init; } = null;

    /// <summary>
    /// Built-in colour/typography theme. Default: [`HtmlTheme::Unstyled`].
    /// </summary>
    [JsonPropertyName("theme")]
    public HTMLTheme Theme { get; init; } = HTMLTheme.Unstyled;

    /// <summary>
    /// CSS class prefix applied to every emitted class name.
    ///
    /// Default: `"kb-"`. Change this if your host application already uses
    /// classes that start with `kb-`.
    /// </summary>
    [JsonPropertyName("class_prefix")]
    public string ClassPrefix { get; init; } = "";

    /// <summary>
    /// When `true` (default), write the resolved CSS into a `<style>` block
    /// immediately after the opening `<div class="{prefix}doc">`.
    ///
    /// Set to `false` to emit only the structural markup and wire up your
    /// own stylesheet targeting the `kb-*` class names.
    /// </summary>
    [JsonPropertyName("embed_css")]
    public bool EmbedCSS { get; init; } = true;


    /// <summary>
    /// Parse a <see cref="HTMLOutputConfig"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static HTMLOutputConfig FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HTMLOutputConfig>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse HTMLOutputConfig from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse HTMLOutputConfig from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };

    public static HTMLOutputConfig Default()
    {
        var nativeResult = NativeMethods.HTMLOutputConfigDefault();
var jsonPtr = NativeMethods.HTMLOutputConfigToJson(nativeResult);
var json = global::System.Runtime.InteropServices.Marshal.PtrToStringUTF8(jsonPtr);
NativeMethods.FreeString(jsonPtr);
NativeMethods.HTMLOutputConfigFree(nativeResult);
return JsonSerializer.Deserialize<HTMLOutputConfig>(json ?? "null", JsonOptions)!;
    }
}
