// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ba1e82ea2e487d1c017231b78e4f4e61ea86ba56d9ef4fc07079df1d559678be
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class HwpImage
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonConverter(typeof(ByteArrayToIntArrayConverter))]
    [JsonPropertyName("data")]
    public byte[] Data { get; set; } = Array.Empty<byte>();


    /// <summary>
    /// Parse a <see cref="HwpImage"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static HwpImage FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<HwpImage>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse HwpImage from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse HwpImage from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
