// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7c8ab65ef7786c18581b26679a39f3f0f9ad6986ba00146af2dee68e6b66471d
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
