// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:97822be1b837435ff59fbaae5993fa84b7720ee0cb845adf6db52098eb592a2f
#nullable enable

using System;

namespace Kreuzberg;

public class ImageProcessingException : KreuzbergErrorException
{
    public ImageProcessingException(string message) : base(message) { }

    public ImageProcessingException(string message, Exception innerException) : base(message, innerException) { }
}
