// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3c1b4241dd809e23f9e6bf8988ee80031e49700b8e70c1c5ef34aa4ca1a856be
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Types of inline elements in Djot./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum InlineType
{[JsonPropertyName("text")]
    Text,[JsonPropertyName("strong")]
    Strong,[JsonPropertyName("emphasis")]
    Emphasis,[JsonPropertyName("highlight")]
    Highlight,[JsonPropertyName("subscript")]
    Subscript,[JsonPropertyName("superscript")]
    Superscript,[JsonPropertyName("insert")]
    Insert,[JsonPropertyName("delete")]
    Delete,[JsonPropertyName("code")]
    Code,[JsonPropertyName("link")]
    Link,[JsonPropertyName("image")]
    Image,[JsonPropertyName("span")]
    Span,[JsonPropertyName("math")]
    Math,[JsonPropertyName("raw_inline")]
    RawInline,[JsonPropertyName("footnote_ref")]
    FootnoteRef,[JsonPropertyName("symbol")]
    Symbol,}
