// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:97d7376f79550e91d8204c2a5631a764158d78769765a37a24c59761117e19cd
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
