// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b895e09db104c04d3ac76b78cde77fec00ed4e498087c82c8506361f6b118779
#nullable enable

using System;

namespace Kreuzberg;

public class IoException : KreuzbergErrorException
{
    public IoException(string message) : base(message) { }

    public IoException(string message, Exception innerException) : base(message, innerException) { }
}
