// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:845394b2e35d35274860a8c9f5ef12f4eb9929cb72367d47c85c111bfe7a06a4
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Keyword algorithm selection.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum KeywordAlgorithm
{    /// <summary>
    /// YAKE (Yet Another Keyword Extractor) - statistical approach
    /// </summary>
    [JsonPropertyName("yake")]
    Yake,    /// <summary>
    /// RAKE (Rapid Automatic Keyword Extraction) - co-occurrence based
    /// </summary>
    [JsonPropertyName("rake")]
    Rake,}
