// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b06a2e80df9c187c10ef195b058b1e572adcc5d1c761abccd5a47367d0f12a2e
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// The 17 canonical document layout classes.
///
/// All model backends (RT-DETR, YOLO, etc.) map their native class IDs
/// to this shared set. Models with fewer classes (DocLayNet: 11, PubLayNet: 5)
/// map to the closest equivalent.
///
/// Wire format is snake_case in all serializers (JSON, TOML, YAML).
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LayoutClass2
{    [JsonPropertyName("caption")]
    Caption,    [JsonPropertyName("footnote")]
    Footnote,    [JsonPropertyName("formula")]
    Formula,    [JsonPropertyName("list_item")]
    ListItem,    [JsonPropertyName("page_footer")]
    PageFooter,    [JsonPropertyName("page_header")]
    PageHeader,    [JsonPropertyName("picture")]
    Picture,    [JsonPropertyName("section_header")]
    SectionHeader,    [JsonPropertyName("table")]
    Table,    [JsonPropertyName("text")]
    Text,    [JsonPropertyName("title")]
    Title,    [JsonPropertyName("document_index")]
    DocumentIndex,    [JsonPropertyName("code")]
    Code,    [JsonPropertyName("checkbox_selected")]
    CheckboxSelected,    [JsonPropertyName("checkbox_unselected")]
    CheckboxUnselected,    [JsonPropertyName("form")]
    Form,    [JsonPropertyName("key_value_region")]
    KeyValueRegion,}
