// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7fb443c2fa83f2aedf70d47660be0dc3146d422b2de4cf0cd51dfdd494624b57
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Link type classification.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{    /// <summary>
    /// Anchor link (#section)
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,    /// <summary>
    /// Internal link (same domain)
    /// </summary>
    [JsonPropertyName("internal")]
    Internal,    /// <summary>
    /// External link (different domain)
    /// </summary>
    [JsonPropertyName("external")]
    External,    /// <summary>
    /// Email link (mailto:)
    /// </summary>
    [JsonPropertyName("email")]
    Email,    /// <summary>
    /// Phone link (tel:)
    /// </summary>
    [JsonPropertyName("phone")]
    Phone,    /// <summary>
    /// Other link type
    /// </summary>
    [JsonPropertyName("other")]
    Other,}
