// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2aa135e6ba085a0992f75975b41222717aceca481b3d635d31998b223ed9c072
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Link type classification./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum LinkType
{/// <summary>    /// Anchor link (#section)    /// </summary>
[JsonPropertyName("anchor")]
    Anchor,/// <summary>    /// Internal link (same domain)    /// </summary>
[JsonPropertyName("internal")]
    Internal,/// <summary>    /// External link (different domain)    /// </summary>
[JsonPropertyName("external")]
    External,/// <summary>    /// Email link (mailto:)    /// </summary>
[JsonPropertyName("email")]
    Email,/// <summary>    /// Phone link (tel:)    /// </summary>
[JsonPropertyName("phone")]
    Phone,/// <summary>    /// Other link type    /// </summary>
[JsonPropertyName("other")]
    Other,}
