// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:074486159a0339d8eafbea497788dc678d26342493056451dac55a8f53f84e0b
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
