// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a81e30a624b18221e2ff9575d7722674c98f04bb481444e2490e4f93221eebc1
#nullable enable

using System;

namespace Kreuzberg;

public class LockPoisonedException : KreuzbergErrorException
{
    public LockPoisonedException(string message) : base(message) { }

    public LockPoisonedException(string message, Exception innerException) : base(message, innerException) { }
}
