// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:31f849ea9766dc17d85f687224f9b442ce8de9d248a0f074cc3efd9d2e4e9371
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A merged chunk produced by [`merge_segments`].
/// </summary>
public sealed class MergedChunk
{
    [JsonPropertyName("text")]
    public string Text { get; set; } = "";

    [JsonPropertyName("byte_start")]
    public ulong ByteStart { get; set; } = 0;

    [JsonPropertyName("byte_end")]
    public ulong ByteEnd { get; set; } = 0;


    /// <summary>
    /// Parse a <see cref="MergedChunk"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static MergedChunk FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<MergedChunk>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse MergedChunk from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse MergedChunk from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
