// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2cf9252a17a17849f92bfdd2fee74aae6bf3cb0a0fd800dca28c5f386300dcc8
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
