// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:22aac617633f44015779d1196020a711b883ebe00fbb19a20fe3c0bf5ea76ad5
#nullable enable

using System;

namespace Kreuzberg;

public class MissingDependencyException : KreuzbergErrorException
{
    public MissingDependencyException(string message) : base(message) { }

    public MissingDependencyException(string message, Exception innerException) : base(message, innerException) { }
}
