// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8102bc3548f72ce110f0203593b65bee587855a669f0825ef4f032c6acb409eb
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// OCR backend types./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrBackendType
{/// <summary>    /// Tesseract OCR (native Rust binding)    /// </summary>
[JsonPropertyName("tesseract")]
    Tesseract,/// <summary>    /// EasyOCR (Python-based, via FFI)    /// </summary>
[JsonPropertyName("easyocr")]
    EasyOcr,/// <summary>    /// PaddleOCR (Python-based, via FFI)    /// </summary>
[JsonPropertyName("paddleocr")]
    PaddleOcr,/// <summary>    /// Custom/third-party OCR backend    /// </summary>
[JsonPropertyName("custom")]
    Custom,}
