// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1cdab52b9c0c3ea836607e1e356ab8997533d2e17424201c2442983050a808ab
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// OCR backend types.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrBackendType
{    /// <summary>
    /// Tesseract OCR (native Rust binding)
    /// </summary>
    [JsonPropertyName("tesseract")]
    Tesseract,    /// <summary>
    /// EasyOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("easyocr")]
    EasyOcr,    /// <summary>
    /// PaddleOCR (Python-based, via FFI)
    /// </summary>
    [JsonPropertyName("paddleocr")]
    PaddleOcr,    /// <summary>
    /// Custom/third-party OCR backend
    /// </summary>
    [JsonPropertyName("custom")]
    Custom,}
