// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:6a60f022e930a48591bc23d297dd71343c14ee05c04e2b1df476563497fe5366
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Hierarchical level of an OCR element./// /// Maps to Tesseract's page segmentation hierarchy and provides/// equivalent semantics for PaddleOCR./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OcrElementLevel
{/// <summary>    /// Individual word    /// </summary>
[JsonPropertyName("word")]
    Word,/// <summary>    /// Line of text (default for PaddleOCR)    /// </summary>
[JsonPropertyName("line")]
    Line,/// <summary>    /// Paragraph or text block    /// </summary>
[JsonPropertyName("block")]
    Block,/// <summary>    /// Page-level element    /// </summary>
[JsonPropertyName("page")]
    Page,}
