// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7551077eaf84dec30b8ec44ff25d594f51711bda7c1b57af7383ccd301dfb8ed
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
