// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b087825f15af206166efe479d752b4cc1ffeee3732023e7c1fdcb76e2371f095
#nullable enable

using System;

namespace Kreuzberg;

public class OcrException : KreuzbergErrorException
{
    public OcrException(string message) : base(message) { }

    public OcrException(string message, Exception innerException) : base(message, innerException) { }
}
