// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8dd2bbbb206a34d6427afe34a09a36e62115f8e24913644aae0d842ac2fb6f4a
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
