// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5e7065d433e4a81f62b4e46d3608d41028261ebfb41da525964db08e123eae79
#nullable enable

using System;

namespace Kreuzberg;

public class OtherException : KreuzbergErrorException
{
    public OtherException(string message) : base(message) { }

    public OtherException(string message, Exception innerException) : base(message, innerException) { }
}
