// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9282200eec31aa96d7b50d3be9fd0358f015a966ecfaf85ffbba5af9e7f78a93
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Output format for extraction results.
///
/// Controls the format of the `content` field in `ExtractionResult`.
/// When set to `Markdown`, `Djot`, or `Html`, the output will be formatted
/// accordingly. `Plain` returns the raw extracted text.
/// `Structured` returns JSON with full OCR element data including bounding
/// boxes and confidence scores.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum OutputFormat
{    /// <summary>
    /// Plain text content only (default)
    /// </summary>
    [JsonPropertyName("plain")]
    Plain,    /// <summary>
    /// Markdown format
    /// </summary>
    [JsonPropertyName("markdown")]
    Markdown,    /// <summary>
    /// Djot markup format
    /// </summary>
    [JsonPropertyName("djot")]
    Djot,    /// <summary>
    /// HTML format
    /// </summary>
    [JsonPropertyName("html")]
    HTML,    /// <summary>
    /// JSON tree format with heading-driven sections.
    /// </summary>
    [JsonPropertyName("json")]
    JSON,    /// <summary>
    /// Structured JSON format with full OCR element metadata.
    /// </summary>
    [JsonPropertyName("structured")]
    Structured,    /// <summary>
    /// Custom renderer registered via the RendererRegistry.
    /// The string is the renderer name (e.g., "docx", "latex").
    /// </summary>
    [JsonPropertyName("custom")]
    Custom,}
