// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:387216f1e00590029240fb8fcdbba2da09bac84a5143bdfde5955a871218b19b
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Type of paginated unit in a document./// /// Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets)./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PageUnitType
{/// <summary>    /// Standard document pages (PDF, DOCX, images)    /// </summary>
[JsonPropertyName("page")]
    Page,/// <summary>    /// Presentation slides (PPTX, ODP)    /// </summary>
[JsonPropertyName("slide")]
    Slide,/// <summary>    /// Spreadsheet sheets (XLSX, ODS)    /// </summary>
[JsonPropertyName("sheet")]
    Sheet,}
