// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8e80eb5846c7a7dd93f6f6e90c8f5dd4472f48a5bf4873bff22a8b6ffbcb1188
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
