// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d057c69fe0699e81248f0741304f01816856e7ad71de71fd5a39c57ff1fecc56
#nullable enable

using System;

namespace Kreuzberg;

public class ParsingException : KreuzbergErrorException
{
    public ParsingException(string message) : base(message) { }

    public ParsingException(string message, Exception innerException) : base(message, innerException) { }
}
