// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:60c7d3e3d22584910b01cf3057038c77359e0ee9ce25fd6a0be9829afe7dcba7
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
