// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d09ebcc737f3b34465ded97dab8ce6e356a94c0beeac375eaadaf60dea5bbb8b
#nullable enable

using System;

namespace Kreuzberg;

public class PluginException : KreuzbergErrorException
{
    public PluginException(string message) : base(message) { }

    public PluginException(string message, Exception innerException) : base(message, innerException) { }
}
