// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2c5910327aa34e162d5acd9ae71cf213c7a8fd6f9507a4de6495f43f03cd3c3d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Error type for pool operations./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PoolError
{/// <summary>    /// The pool's internal mutex was poisoned.    ///     /// This indicates a panic occurred while holding the lock.    /// The pool is in a locked state and cannot be recovered.    /// </summary>
[JsonPropertyName("lockpoisoned")]
    LockPoisoned,}
