// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:d3a09159fb272fe1b85e10d705315e36e4169bcccf315b5a77c990f35853181a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Processing stages for post-processors.
///
/// Post-processors are executed in stage order (Early → Middle → Late).
/// Use stages to control the order of post-processing operations.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ProcessingStage
{    /// <summary>
    /// Early stage - foundational processing.
    ///
    /// Use for:
    /// - Language detection
    /// - Character encoding normalization
    /// - Entity extraction (NER)
    /// - Text quality scoring
    /// </summary>
    [JsonPropertyName("early")]
    Early,    /// <summary>
    /// Middle stage - content transformation.
    ///
    /// Use for:
    /// - Keyword extraction
    /// - Token reduction
    /// - Text summarization
    /// - Semantic analysis
    /// </summary>
    [JsonPropertyName("middle")]
    Middle,    /// <summary>
    /// Late stage - final enrichment.
    ///
    /// Use for:
    /// - Custom user hooks
    /// - Analytics/logging
    /// - Final validation
    /// - Output formatting
    /// </summary>
    [JsonPropertyName("late")]
    Late,}
