// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:5aa895b6e025f063f312b0474d189961d219d1e8846248ee9b1f990b8691aa6a
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Page Segmentation Mode for Tesseract OCR/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PsmMode
{[JsonPropertyName("osdonly")]
    OsdOnly,[JsonPropertyName("autoosd")]
    AutoOsd,[JsonPropertyName("autoonly")]
    AutoOnly,[JsonPropertyName("auto")]
    Auto,[JsonPropertyName("singlecolumn")]
    SingleColumn,[JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,[JsonPropertyName("singleblock")]
    SingleBlock,[JsonPropertyName("singleline")]
    SingleLine,[JsonPropertyName("singleword")]
    SingleWord,[JsonPropertyName("circleword")]
    CircleWord,[JsonPropertyName("singlechar")]
    SingleChar,}
