// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:8b87de2dc78a6f94205f48c6330a39ad0a627ba0f77e77a6d24cdada69264075
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Page Segmentation Mode for Tesseract OCR
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum PSMMode
{    [JsonPropertyName("osdonly")]
    OsdOnly,    [JsonPropertyName("autoosd")]
    AutoOsd,    [JsonPropertyName("autoonly")]
    AutoOnly,    [JsonPropertyName("auto")]
    Auto,    [JsonPropertyName("singlecolumn")]
    SingleColumn,    [JsonPropertyName("singleblockvertical")]
    SingleBlockVertical,    [JsonPropertyName("singleblock")]
    SingleBlock,    [JsonPropertyName("singleline")]
    SingleLine,    [JsonPropertyName("singleword")]
    SingleWord,    [JsonPropertyName("circleword")]
    CircleWord,    [JsonPropertyName("singlechar")]
    SingleChar,}
