// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7dc2c1fe2692aef6bbc51db46ca49928f8eccba2a75cdb7d63810497c8725d43
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReductionLevel
{    [JsonPropertyName("off")]
    Off,    [JsonPropertyName("light")]
    Light,    [JsonPropertyName("moderate")]
    Moderate,    [JsonPropertyName("aggressive")]
    Aggressive,    [JsonPropertyName("maximum")]
    Maximum,}
