// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:c2f6b923ff59b33bf2b7f0910ac1c348eeeb43074fe8ac349ab41bc984a15658
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ReductionLevel
{[JsonPropertyName("off")]
    Off,[JsonPropertyName("light")]
    Light,[JsonPropertyName("moderate")]
    Moderate,[JsonPropertyName("aggressive")]
    Aggressive,[JsonPropertyName("maximum")]
    Maximum,}
