// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2c293f8fa013b941c2c4a27fa27765f53556ad200d28be90e66a7d01709ffce4
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Result-shape selection for extraction results.
///
/// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,
/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content
/// blob vs. an element-based decomposition.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ResultFormat
{    /// <summary>
    /// Unified format with all content in `content` field
    /// </summary>
    [JsonPropertyName("unified")]
    Unified,    /// <summary>
    /// Element-based format with semantic element extraction
    /// </summary>
    [JsonPropertyName("element_based")]
    ElementBased,}
