// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a12efbcb20bafe840072cfc5930a1c1164ac6c46e6b03358f267e378887a938d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>/// Result-shape selection for extraction results./// /// Distinct from `OutputFormat` (which controls rendering — Plain, Markdown,/// HTML, etc.). `ResultFormat` controls the *shape* of the result: a unified content/// blob vs. an element-based decomposition./// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum ResultFormat
{/// <summary>    /// Unified format with all content in `content` field    /// </summary>
[JsonPropertyName("unified")]
    Unified,/// <summary>    /// Element-based format with semantic element extraction    /// </summary>
[JsonPropertyName("element_based")]
    ElementBased,}
