// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:0a4f5ea32f98cf72957a613eb1d96f97875cf539f3d125c82484382b6c95657b
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
