// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:894e0763e53682f62357b29a912677a9a08ffa08d5dcdc792d116e463ae2ad4e
#nullable enable

using System;

namespace Kreuzberg;

public class SecurityException : KreuzbergErrorException
{
    public SecurityException(string message) : base(message) { }

    public SecurityException(string message, Exception innerException) : base(message, innerException) { }
}
