// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:7ac7f20457a9fb19a0210d43ae56910cff4d663b09f6a1e4e9ac8bbcad50e954
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
