// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:9e8a9397b1df63715381f71ccbca5d7eb4079d117ce234c112c073456efbbe5f
#nullable enable

using System;

namespace Kreuzberg;

public class SerializationException : KreuzbergErrorException
{
    public SerializationException(string message) : base(message) { }

    public SerializationException(string message, Exception innerException) : base(message, innerException) { }
}
