// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:1a55bfc4bc32ee5b6bdb44535b72ea94e77f05a11f99e5ee0d508c9a2d3d8a17
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class StringBufferPoolSafeHandle : SafeHandle
{
    internal StringBufferPoolSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.StringBufferPoolFree(handle);
        return true;
    }
}
/// <summary>/// Convenience type alias for a pooled String./// </summary>
public sealed class StringBufferPool : IDisposable
{
    private readonly StringBufferPoolSafeHandle _safeHandle;

    internal StringBufferPool(IntPtr handle)
    {
        _safeHandle = new StringBufferPoolSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
