// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cd8304d1e8456851ec8fb5bec6c1fdfae3c242f37e7c2e2bd76b7a7f488cd382
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

public sealed class StructuredDataResult
{
    [JsonPropertyName("content")]
    public string Content { get; set; } = "";

    [JsonPropertyName("format")]
    public string Format { get; set; } = "";

    [JsonPropertyName("metadata")]
    public Dictionary<string, string> Metadata { get; set; } = default!;

    [JsonPropertyName("text_fields")]
    public List<string> TextFields { get; set; } = [];


    /// <summary>
    /// Parse a <see cref="StructuredDataResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static StructuredDataResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<StructuredDataResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse StructuredDataResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse StructuredDataResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
