// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8e81f9bf949e50d2e30e226960719eba04d614c075153ea802331b0790074d7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Column widths from `<w:tblGrid>`.
/// </summary>
public sealed record TableTableGrid
{
    [JsonPropertyName("columns")]
    public List<int> Columns { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="TableTableGrid"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static TableTableGrid FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<TableTableGrid>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse TableTableGrid from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse TableTableGrid from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
