// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:f2df41726c8455be6aef732d00d8af9b3ae3786755150bb1dab10feebff78961
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// Extracted table from OCR
/// </summary>
public sealed record Table2
{
    [JsonPropertyName("cells")]
    public List<List<string>> Cells { get; init; } = [];

    [JsonPropertyName("markdown")]
    public required string Markdown { get; init; }

    [JsonPropertyName("page_number")]
    public int PageNumber { get; init; } = 0;


    /// <summary>
    /// Parse a <see cref="Table2"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static Table2 FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<Table2>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse Table2 from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse Table2 from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
