// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:2383487dbcb552d617341826ad10aa16ed69ce8e5b4dab9da259150734b2a6b4
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
