// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:23431676fd63509e7309df73ab387cd148d0c83d9573a5b333a119a09f963364
#nullable enable

using System;

namespace Kreuzberg;

public class TimeoutException : KreuzbergErrorException
{
    public TimeoutException(string message) : base(message) { }

    public TimeoutException(string message, Exception innerException) : base(message, innerException) { }
}
