// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b2d4ebdf647112cb4f502d1a7fb23c91a60740088ef0a3f50d855fb157365cb3
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class TracingLayerSafeHandle : SafeHandle
{
    internal TracingLayerSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.TracingLayerFree(handle);
        return true;
    }
}
/// <summary>/// A [`tower::Layer`] that wraps each extraction in a semantic tracing span./// </summary>
public sealed class TracingLayer : IDisposable
{
    private readonly TracingLayerSafeHandle _safeHandle;

    internal TracingLayer(IntPtr handle)
    {
        _safeHandle = new TracingLayerSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
