// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:647a602526db498be7887877a726fe10820a1ff32212d2743306756c5cb84f13
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Type of list detection.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TransformListType
{    /// <summary>
    /// Bullet points (-, *, •, etc.)
    /// </summary>
    [JsonPropertyName("bullet")]
    Bullet,    /// <summary>
    /// Numbered lists (1., 2., etc.)
    /// </summary>
    [JsonPropertyName("numbered")]
    Numbered,    /// <summary>
    /// Lettered lists (a., b., A., B., etc.)
    /// </summary>
    [JsonPropertyName("lettered")]
    Lettered,    /// <summary>
    /// Indented items
    /// </summary>
    [JsonPropertyName("indented")]
    Indented,}
