// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:3cc1257c48d64e093508fdea8fdb91ae2c82a9040b00804847263162363786b1
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
