// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:a6b49a314280f1c9316e492972a0474a4dd3deb9e646de1e2d6d23db06ba160a
#nullable enable

using System;

namespace Kreuzberg;

public class UnsupportedFormatException : KreuzbergErrorException
{
    public UnsupportedFormatException(string message) : base(message) { }

    public UnsupportedFormatException(string message, Exception innerException) : base(message, innerException) { }
}
