// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:d0e71a8579a4b0f31d2a296aaef332ba9663d00861d2181c049dd8127f4ad224
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// A URI extracted from a document.
///
/// Represents any link, reference, or resource pointer found during extraction.
/// The `kind` field classifies the URI semantically, while `label` carries
/// optional human-readable display text.
/// </summary>
public sealed record URI
{
    /// <summary>
    /// The URL or path string.
    /// </summary>
    [JsonPropertyName("url")]
    public required string URL { get; init; }

    /// <summary>
    /// Optional display text / label for the link.
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; } = null;

    /// <summary>
    /// Optional page number where the URI was found (1-indexed).
    /// </summary>
    [JsonPropertyName("page")]
    public uint? Page { get; init; } = null;

    /// <summary>
    /// Semantic classification of the URI.
    /// </summary>
    [JsonPropertyName("kind")]
    public required URIKind Kind { get; init; }


    /// <summary>
    /// Parse a <see cref="URI"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static URI FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<URI>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse URI from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse URI from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
