// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:fc63b48670dfea8eb47a0ed7d09a9377af7d4f0302061bec85b072773d2ed48d
#nullable enable

using System;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;
/// <summary>
/// Semantic classification of an extracted URI.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum URIKind
{    /// <summary>
    /// A clickable hyperlink (web URL, file link).
    /// </summary>
    [JsonPropertyName("hyperlink")]
    Hyperlink,    /// <summary>
    /// An image or media resource reference.
    /// </summary>
    [JsonPropertyName("image")]
    Image,    /// <summary>
    /// An internal anchor or cross-reference target.
    /// </summary>
    [JsonPropertyName("anchor")]
    Anchor,    /// <summary>
    /// A citation or bibliographic reference (DOI, academic ref).
    /// </summary>
    [JsonPropertyName("citation")]
    Citation,    /// <summary>
    /// A general reference (e.g. `\ref{}` in LaTeX, `:ref:` in RST).
    /// </summary>
    [JsonPropertyName("reference")]
    Reference,    /// <summary>
    /// An email address (`mailto:` link or bare email).
    /// </summary>
    [JsonPropertyName("email")]
    Email,}
