// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:b4a9d3ec863c98b5d72525fff15b3e3f01131cd30b5d51eb38e7f6ec84a8deda
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
