// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:30915808a7e8a974ded3664a96ebed84066bfaa5a072b944244b989dcbedebb9
#nullable enable

using System;

namespace Kreuzberg;

public class ValidationException : KreuzbergErrorException
{
    public ValidationException(string message) : base(message) { }

    public ValidationException(string message, Exception innerException) : base(message, innerException) { }
}
