// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b4ef6308974feadefaabd9d4969d68ac087a1303cfc665cca0b9e5c9296ae1a9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// XML extraction result.
///
/// Contains extracted text content from XML files along with
/// structural statistics about the XML document.
/// </summary>
public sealed record XMLExtractionResult
{
    /// <summary>
    /// Extracted text content (XML structure filtered out)
    /// </summary>
    [JsonPropertyName("content")]
    public required string Content { get; init; }

    /// <summary>
    /// Total number of XML elements processed
    /// </summary>
    [JsonPropertyName("element_count")]
    public ulong ElementCount { get; init; } = 0;

    /// <summary>
    /// List of unique element names found (sorted)
    /// </summary>
    [JsonPropertyName("unique_elements")]
    public List<string> UniqueElements { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="XMLExtractionResult"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static XMLExtractionResult FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<XMLExtractionResult>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse XMLExtractionResult from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse XMLExtractionResult from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
