// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6adde66829a77325615e17d4b976a24584887209c579af5d2dd38d526d440f63
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
#nullable enable

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Kreuzberg;

/// <summary>
/// XML metadata extracted during XML parsing.
///
/// Provides statistics about XML document structure.
/// </summary>
public sealed record XMLMetadata
{
    /// <summary>
    /// Total number of XML elements processed
    /// </summary>
    [JsonPropertyName("element_count")]
    public uint ElementCount { get; init; } = 0;

    /// <summary>
    /// List of unique element tag names (sorted)
    /// </summary>
    [JsonPropertyName("unique_elements")]
    public List<string> UniqueElements { get; init; } = [];


    /// <summary>
    /// Parse a <see cref="XMLMetadata"/> from a JSON string.
    /// </summary>
    /// <exception cref="KreuzbergException">When the JSON cannot be deserialised.</exception>
    public static XMLMetadata FromJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<XMLMetadata>(json, JsonOptions)
                ?? throw new KreuzbergException($"Failed to parse XMLMetadata from JSON: deserializer returned null");
        }
        catch (KreuzbergException)
        {
            throw;
        }
        catch (Exception e)
        {
            throw new KreuzbergException($"Failed to parse XMLMetadata from JSON: {e.Message}", e);
        }
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
        Converters = { new JsonStringEnumConverter(JsonNamingPolicy.SnakeCaseLower) },
    };
}
