// This file is auto-generated by alef. DO NOT EDIT.
// alef:hash:f7e0f6fd67498dad9c5c70c006d03dd8e5ed99cc529800478ebbb12bd597b725
#nullable enable

using System;
using Microsoft.Win32.SafeHandles;
using System.Runtime.InteropServices;
namespace Kreuzberg;

internal sealed class ZipBombValidatorSafeHandle : SafeHandle
{
    internal ZipBombValidatorSafeHandle(IntPtr handle) : base(IntPtr.Zero, true)
    {
        SetHandle(handle);
    }

    public override bool IsInvalid => handle == IntPtr.Zero;

    protected override bool ReleaseHandle()
    {
        NativeMethods.ZipBombValidatorFree(handle);
        return true;
    }
}
/// <summary>/// Helper struct for validating ZIP archives for security issues./// </summary>
public sealed class ZipBombValidator : IDisposable
{
    private readonly ZipBombValidatorSafeHandle _safeHandle;

    internal ZipBombValidator(IntPtr handle)
    {
        _safeHandle = new ZipBombValidatorSafeHandle(handle);
    }

    internal IntPtr Handle => _safeHandle.DangerousGetHandle();

    public void Dispose() => _safeHandle.Dispose();

}
