// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6192a4d2025bf7fc4103b172a5bb5db8877a3d3bf59ce67f9d5ccdfe3648a63e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import { defineConfig } from "vitest/config";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [wasm()],
  test: {
    include: ["tests/**/*.test.ts"],
    testTimeout: 30000,
    setupFiles: ["./setup.ts"],
  },
});
