# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:711823750e129f38a1d1611a084980e8e23e881d773b48566ec5082c0341d921
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# E2e tests for category: registry_operations

test_that("extensions_docx: Get file extensions for DOCX MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document")
  expect_true(TRUE)
})

test_that("extensions_html: Get file extensions for HTML MIME type", {
  result <- get_extensions_for_mime(mime_type = "text/html")
  expect_true(TRUE)
})

test_that("extensions_pdf: Get file extensions for PDF MIME type", {
  result <- get_extensions_for_mime(mime_type = "application/pdf")
  expect_true(TRUE)
  expect_true(grepl("pdf", result, fixed = TRUE))
})
