<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:01f8354d2b3fd0ab1f6b9e8c1e45cde03e17e298e63eefbde9a644608372805b
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * OpenAPI documentation structure.
 *
 * Defines all endpoints, request/response schemas, and examples
 * for the Kreuzberg document extraction API.
 */
final class ApiDoc
{
}
