<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:abec2fa993cad778caf41a7f961fa2dc1ecbbff86366ded8370438036e028493
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Convenience type alias for a pooled Vec<u8>.
 */
final class ByteBufferPool
{
}
