<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a3da85c9f28809d3563c8ff93827c588e28b8c62bf30d9251f141819e7e50ba7
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Custom properties from docProps/custom.xml
 *
 * Maps property names to their values. Values are converted to JSON types
 * based on the VT (Variant Type) specified in the XML.
 */
final class CustomProperties
{
}
