<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3aa5edb9264aeaa78c88385269e99048584aeb09d4cfec84c35704b8196f28d5
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Extraction response (list of results).
 */
final class ExtractResponse
{
}
