<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:5785b962cb45adc283ab8fc99c09483ad78a0ae95704de21c3a85c3c7aefa663
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Extractor for Hangul Word Processor XML (.hwpx) files.
 *
 * Supports HWPX (Open HWPML), the ZIP-based XML successor to the binary HWP 5.0 format.
 */
final class HwpxExtractor
{
    public function name(): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public function version(): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public function initialize(): void
    {
    }
    public function shutdown(): void
    {
    }
    public function description(): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public function author(): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public function extractBytes(string $content, string $mime_type, ExtractionConfig $config): string
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    /**
     * @return array<string>
     */
    public function supportedMimeTypes(): array
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public function priority(): int
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
    public static function default(): HwpxExtractor
    {
        throw new \RuntimeException('Not implemented — provided by the native extension.');
    }
}
