<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:783dd9245b95fa42648069548c330558f48790bba1739d903552bf1a68abe53f
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
final class StreamReader
{
}
