<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:945be32b1e6e81a49105500a5b704dadad92bc9146550d4359ae8aceca4ffd2e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Convenience type alias for a pooled String.
 */
final class StringBufferPool
{
}
