<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:a963a388fa787eed317ad5b8239172156f775b8a9231f87d59ab1e7f74d8bf7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * A [`tower::Layer`] that wraps each extraction in a semantic tracing span.
 */
final class TracingLayer
{
}
