<?php
// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:59ce56cbdb58e903ef51b50a76ac99dd8cf0d8322d67ab4060c553fd9bd94f7d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
declare(strict_types=1);
namespace Kreuzberg;
/**
 * Helper struct for validating ZIP archives for security issues.
 */
final class ZipBombValidator
{
}
