# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:98872e4ce465618930f294f54c5895f2c99ab513704d63ad8345d76819934dcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
library(testthat)
devtools::load_all("../../packages/r")

testthat::set_max_fails(Inf)
.script_dir <- tryCatch(dirname(normalizePath(sys.frame(1)$ofile)), error = function(e) getwd())
test_dir(file.path(.script_dir, "tests"))
