# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ff2fa38ef5d4f5b3babb7471714eb6b814a5a93fc8d59f0585f8195855a48785
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

module Kreuzberg
  VERSION = '5.0.0.pre.rc.1'
end
