# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:176280c917981caf3320476cbac822e8c511d6e47a93a0a58fd607a0beaeb9c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
# frozen_string_literal: true

require_relative 'kreuzberg/version'
require_relative 'kreuzberg/native'

module Kreuzberg
  # Re-export all types and functions from native extension
end
