// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:22922279385f18c8ecbabbd81991a821507e52c75f349a1add65b7970943f7a9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Hardware acceleration configuration for ONNX Runtime models.
 *
 * Controls which execution provider (CPU, CoreML, CUDA, TensorRT) is used
 * for inference in layout detection and embedding generation.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class AccelerationConfigBuilder {

    @JsonProperty("provider")
    private ExecutionProviderType provider = null;
    @JsonProperty("device_id")
    private int deviceId = 0;

    /** Sets the provider field. */
    @JsonProperty("provider")
    public AccelerationConfigBuilder withProvider(final ExecutionProviderType value) {
        this.provider = value;
        return this;
    }

    /** Sets the deviceId field. */
    @JsonProperty("device_id")
    public AccelerationConfigBuilder withDeviceId(final int value) {
        this.deviceId = value;
        return this;
    }

    /** Builds the AccelerationConfig instance. */
    public AccelerationConfig build() {
        return new AccelerationConfig(
            provider,
            deviceId
        );
    }
}
