// DO NOT EDIT - auto-generated by alef
// alef:hash:8ef4481542f1d863fb4bbb28858e7939899b52a89c47431dd71e1dfcd5a48d26
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
