// DO NOT EDIT - auto-generated by alef
// alef:hash:bd051d8c312e077af92b0c251c877924ffaf2da35b43437702a918c8325ec00a
package dev.kreuzberg;

public class CacheException extends KreuzbergErrorException {
    /** Creates a new CacheException with the given message. */
    public CacheException(final String message) {
        super(message);
    }

    /** Creates a new CacheException with the given message and cause. */
    public CacheException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
