// DO NOT EDIT - auto-generated by alef
// alef:hash:35b58b28a5d444fa6147896c25bcba1c2e3ac69422c46fdb6aec0840482966c7
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
