// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3e3ef55511f7789c9cdefda94e5528fdf23c8ff219846740fccadb95cdb58c6d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import org.jspecify.annotations.Nullable;

/**
 * MIME type detection response.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record DetectResponse(
    @JsonProperty("mime_type") String mimeType,
    @Nullable String filename
) {

    /**
     * Parse a {@code DetectResponse} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static DetectResponse fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, DetectResponse.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse DetectResponse from JSON: " + e.getMessage(), e);
        }
    }
}
