// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b78271bb1670259cfac4b00326fc8dad36a1747c2bb0a3b3a5f5bd16073f1b68
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Whether the drawing is inline or anchored.
 */
public enum DrawingType {
    Inline("inline"),
    Anchored("anchored");

    /** The string value. */
    private final String value;

    DrawingType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static DrawingType fromValue(final String value) {
        for (DrawingType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
