// DO NOT EDIT - auto-generated by alef
// alef:hash:269db46cee3b46502aa91a5598ce9489c3612815417bf863819cf2defce9ad70
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
