// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:cff3036a709d97166b82b5948496fbd446e4b14b20bd04ea79dceceba7a27b51
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * EPUB metadata (Dublin Core extensions).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EpubMetadata.Builder.class)
public record EpubMetadata(
    @Nullable String coverage,
    @Nullable @JsonProperty("dc_format") String dcFormat,
    @Nullable String relation,
    @Nullable String source,
    @Nullable @JsonProperty("dc_type") String dcType,
    @Nullable @JsonProperty("cover_image") String coverImage
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code EpubMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static EpubMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, EpubMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse EpubMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
