// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8da194f8f7ffa2cc517a73a71a0f82237cf5fc835ff1136d0865989d686d94dd
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Excel/spreadsheet format metadata.
 *
 * Identifies the document as a spreadsheet source via the {@code FormatMetadata::Excel}
 * discriminant. Sheet count and sheet names are stored inside this struct.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExcelMetadata.Builder.class)
public record ExcelMetadata(
    /**
     * Number of sheets in the workbook.
     */
    @Nullable @JsonProperty("sheet_count") Integer sheetCount,
    /**
     * Names of all sheets in the workbook.
     */
    @Nullable @JsonProperty("sheet_names") List<String> sheetNames
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code ExcelMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ExcelMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ExcelMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ExcelMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
