// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8482fea62c0d0d581eaa8b6712ecfa484ddbef34d19c2bc4e845fced0ce9ea5d
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * OCR extraction result
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record ExtractionResult2(
    String content,
    @JsonProperty("mime_type") String mimeType,
    Map<String, Object> metadata,
    List<Table> tables
) {

    /**
     * Parse a {@code ExtractionResult2} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ExtractionResult2 fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ExtractionResult2.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ExtractionResult2 from JSON: " + e.getMessage(), e);
        }
    }
}
