// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9195eb2af4a8744d9217987686da1e1e30bea0de8c5b5eb2637a328ae5d3fc22
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * How the extracted text was produced.
 */
public enum ExtractionMethod2 {
    Native("native"),
    Ocr("ocr"),
    Mixed("mixed");

    /** The string value. */
    private final String value;

    ExtractionMethod2(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static ExtractionMethod2 fromValue(final String value) {
        for (ExtractionMethod2 e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
