// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:122b70c058a5f6d133c0112d98a03573824425ff1139b31cb02ca407d7cba4b8
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Image preprocessing configuration for OCR.
 *
 * These settings control how images are preprocessed before OCR to improve
 * text recognition quality. Different preprocessing strategies work better
 * for different document types.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImagePreprocessingConfig.Builder.class)
public record ImagePreprocessingConfig(
    /**
     * Target DPI for the image (300 is standard, 600 for small text).
     */
    @JsonProperty("target_dpi") int targetDpi,
    /**
     * Auto-detect and correct image rotation.
     */
    @JsonProperty("auto_rotate") boolean autoRotate,
    /**
     * Correct skew (tilted images).
     */
    boolean deskew,
    /**
     * Remove noise from the image.
     */
    boolean denoise,
    /**
     * Enhance contrast for better text visibility.
     */
    @JsonProperty("contrast_enhance") boolean contrastEnhance,
    /**
     * Binarization method: "otsu", "sauvola", "adaptive".
     */
    @JsonProperty("binarization_method") String binarizationMethod,
    /**
     * Invert colors (white text on black → black on white).
     */
    @JsonProperty("invert_colors") boolean invertColors
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code ImagePreprocessingConfig} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static ImagePreprocessingConfig fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, ImagePreprocessingConfig.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse ImagePreprocessingConfig from JSON: " + e.getMessage(), e);
        }
    }
    public ImagePreprocessingConfig{
        if (targetDpi == 0) targetDpi = 300;
    }
    public static ImagePreprocessingConfig defaultInstance() {
        throw new UnsupportedOperationException("defaultInstance is not yet bridged via JNI; use the Builder instead.");
    }
}
