// DO NOT EDIT - auto-generated by alef
// alef:hash:0f3b08c94f6d90b964b6b10053056a758c0f0fd2f4f56702b1ef5f9647ac124e
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
