// DO NOT EDIT - auto-generated by alef
// alef:hash:9068e02b13310de4151a579741b07f1ba4609663d18bfc13743e3a07abc36e49
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
