// DO NOT EDIT - auto-generated by alef
// alef:hash:a2e0d3421346eed873e2eae17bb46b87f18f0cafffe53aacbe7bb84e52ecc634
package dev.kreuzberg;

public class IoException extends KreuzbergErrorException {
    /** Creates a new IoException with the given message. */
    public IoException(final String message) {
        super(message);
    }

    /** Creates a new IoException with the given message and cause. */
    public IoException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
