// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:519bdd4da9b3eaf0e48474ba3d5ca15d92759605f4dfd65018ca3c237ad5d3f6
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * Token usage and cost data for a single LLM call made during extraction.
 *
 * Populated when VLM OCR, structured extraction, or LLM-based embeddings
 * are used. Multiple entries may be present when multiple LLM calls occur
 * within one extraction (e.g. VLM OCR + structured extraction).
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LlmUsage.Builder.class)
public record LlmUsage(
    /**
     * The LLM model identifier (e.g. "openai/gpt-4o", "anthropic/claude-sonnet-4-20250514").
     */
    String model,
    /**
     * The pipeline stage that triggered this LLM call
     * (e.g. "vlm_ocr", "structured_extraction", "embeddings").
     */
    String source,
    /**
     * Number of input/prompt tokens consumed.
     */
    @Nullable @JsonProperty("input_tokens") Long inputTokens,
    /**
     * Number of output/completion tokens generated.
     */
    @Nullable @JsonProperty("output_tokens") Long outputTokens,
    /**
     * Total tokens (input + output).
     */
    @Nullable @JsonProperty("total_tokens") Long totalTokens,
    /**
     * Estimated cost in USD based on the provider's published pricing.
     */
    @Nullable @JsonProperty("estimated_cost") Double estimatedCost,
    /**
     * Why the model stopped generating (e.g. "stop", "length", "content_filter").
     */
    @Nullable @JsonProperty("finish_reason") String finishReason
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code LlmUsage} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static LlmUsage fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, LlmUsage.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse LlmUsage from JSON: " + e.getMessage(), e);
        }
    }
}
