// DO NOT EDIT - auto-generated by alef
// alef:hash:c2ce5b5268209ffd81965b4cea00be2284bc7965c5a697ac5c0feba2619f9ccd
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
