// DO NOT EDIT - auto-generated by alef
// alef:hash:c0bcf7b4d7130c469d34f017dae9127ddd909221aacce3ee9ce82d6a368c7a5c
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
