// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:629eaff0b0ba154ef4bca3c77743f49f09a27801285d7acaac160316a38ebd90
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Confidence scores for an OCR element.
 *
 * Separates detection confidence (how confident that text exists at this location)
 * from recognition confidence (how confident about the actual text content).
 */
@JsonPOJOBuilder(withPrefix = "with")
public class OcrConfidenceBuilder {

    @JsonProperty("detection")
    private Optional<Double> detection = Optional.empty();
    @JsonProperty("recognition")
    private double recognition = 0.0;

    /** Sets the detection field. */
    @JsonProperty("detection")
    public OcrConfidenceBuilder withDetection(final Optional<Double> value) {
        this.detection = value;
        return this;
    }

    /** Sets the recognition field. */
    @JsonProperty("recognition")
    public OcrConfidenceBuilder withRecognition(final double value) {
        this.recognition = value;
        return this;
    }

    /** Builds the OcrConfidence instance. */
    public OcrConfidence build() {
        return new OcrConfidence(
            detection.orElse(null),
            recognition
        );
    }
}
