// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:6b244f25611c52cf2d45a55053fc9058439b80b42eddf5b2305e6a38899696e9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

@JsonDeserialize(builder = OcrCacheStats.Builder.class)
public record OcrCacheStats(
    @JsonProperty("total_files") long totalFiles,
    @JsonProperty("total_size_mb") double totalSizeMb
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code OcrCacheStats} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static OcrCacheStats fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, OcrCacheStats.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse OcrCacheStats from JSON: " + e.getMessage(), e);
        }
    }
}
