// DO NOT EDIT - auto-generated by alef
// alef:hash:13534167c5f71e11b9412c937bda4dbc390b2c171a7ce093788bc3a09e6d1099
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
