// DO NOT EDIT - auto-generated by alef
// alef:hash:8c901060eb4ae4829a0301c6fd935865caea0c1784d825a368fc2ff1d4d8dd0b
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
