// DO NOT EDIT - auto-generated by alef
// alef:hash:1c90b4784e2d520e428924ca55a912fa9fe7b26f6366415635bf2e6f6529b837
package dev.kreuzberg;

public class OtherException extends KreuzbergErrorException {
    /** Creates a new OtherException with the given message. */
    public OtherException(final String message) {
        super(message);
    }

    /** Creates a new OtherException with the given message and cause. */
    public OtherException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
