// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:8b90e4ec9fe27cc02a9877c46a4281dcde5de64d7646b11c222952a708e66daf
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Type of paginated unit in a document.
 *
 * Distinguishes between different types of "pages" (PDF pages, presentation slides, spreadsheet sheets).
 */
public enum PageUnitType {
    /** Standard document pages (PDF, DOCX, images) */
    Page("page"),
    /** Presentation slides (PPTX, ODP) */
    Slide("slide"),
    /** Spreadsheet sheets (XLSX, ODS) */
    Sheet("sheet");

    /** The string value. */
    private final String value;

    PageUnitType(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PageUnitType fromValue(final String value) {
        for (PageUnitType e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
