// DO NOT EDIT - auto-generated by alef
// alef:hash:d090072868a56d4646de2b61eb7cbb0d9029a95f5c965520db87598a39a7f0e6
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
