// DO NOT EDIT - auto-generated by alef
// alef:hash:fa28334e9becb0f59bea562216aa9996e8bfe461cd23d5202c46940b1d59277b
package dev.kreuzberg;

public class ParsingException extends KreuzbergErrorException {
    /** Creates a new ParsingException with the given message. */
    public ParsingException(final String message) {
        super(message);
    }

    /** Creates a new ParsingException with the given message and cause. */
    public ParsingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
