// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:2bf0d72ab3997bef264abed4a04e14a695d34bb4875cbfde291536db8679c631
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * PDF-specific metadata.
 *
 * Contains metadata fields specific to PDF documents that are not in the common
 * {@code Metadata} structure. Common fields like title, authors, keywords, and dates
 * are at the {@code Metadata} level.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PdfMetadata.Builder.class)
public record PdfMetadata(
    /**
     * PDF version (e.g., "1.7", "2.0")
     */
    @Nullable @JsonProperty("pdf_version") String pdfVersion,
    /**
     * PDF producer (application that created the PDF)
     */
    @Nullable String producer,
    /**
     * Whether the PDF is encrypted/password-protected
     */
    @Nullable @JsonProperty("is_encrypted") Boolean isEncrypted,
    /**
     * First page width in points (1/72 inch)
     */
    @Nullable Long width,
    /**
     * First page height in points (1/72 inch)
     */
    @Nullable Long height,
    /**
     * Total number of pages in the PDF document
     */
    @Nullable @JsonProperty("page_count") Integer pageCount
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code PdfMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static PdfMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, PdfMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse PdfMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
