// DO NOT EDIT - auto-generated by alef
// alef:hash:0b9e8d16ca59895035daab8e2b0e0fe42ed93465f77f14c419ced0e73b5afbf3
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
