// DO NOT EDIT - auto-generated by alef
// alef:hash:3981439c1779546376432c72d0a61625007b800b721806d8c8df5f80019f23ab
package dev.kreuzberg;

public class PluginException extends KreuzbergErrorException {
    /** Creates a new PluginException with the given message. */
    public PluginException(final String message) {
        super(message);
    }

    /** Creates a new PluginException with the given message and cause. */
    public PluginException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
