// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:1d27881ce22c8a4129660b83f59cdc7462028616f61fcc2a7df9b67bb340ae9c
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Error type for pool operations.
 */
public enum PoolError {
    /** The pool's internal mutex was poisoned. */
    LockPoisoned("lockpoisoned");

    /** The string value. */
    private final String value;

    PoolError(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PoolError fromValue(final String value) {
        for (PoolError e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
