// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:90c222d9547dd2d6713fea5a4ef1e12a927df462d1f0a2d1bd299aff9f966d37
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import org.jspecify.annotations.Nullable;

/**
 * PowerPoint presentation metadata.
 *
 * Extracted from PPTX files containing slide counts and presentation details.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = PptxMetadata.Builder.class)
public record PptxMetadata(
    /**
     * Total number of slides in the presentation
     */
    @JsonProperty("slide_count") int slideCount,
    /**
     * Names of slides (if available)
     */
    @JsonProperty("slide_names") List<String> slideNames,
    /**
     * Number of embedded images
     */
    @Nullable @JsonProperty("image_count") Integer imageCount,
    /**
     * Number of tables
     */
    @Nullable @JsonProperty("table_count") Integer tableCount
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code PptxMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static PptxMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, PptxMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse PptxMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
