// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:030b84f66df999e20bbb0896853ab8c4b88b6aaf17b709c97b4af342155975a9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Page Segmentation Mode for Tesseract OCR
 */
public enum PSMMode {
    OsdOnly("osdonly"),
    AutoOsd("autoosd"),
    AutoOnly("autoonly"),
    Auto("auto"),
    SingleColumn("singlecolumn"),
    SingleBlockVertical("singleblockvertical"),
    SingleBlock("singleblock"),
    SingleLine("singleline"),
    SingleWord("singleword"),
    CircleWord("circleword"),
    SingleChar("singlechar");

    /** The string value. */
    private final String value;

    PSMMode(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static PSMMode fromValue(final String value) {
        for (PSMMode e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
