// DO NOT EDIT - auto-generated by alef
// alef:hash:725582d767c7c2f1f641548375bdcb6988e7c3eb99cb7e32ca1d0cd235b04f7a
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
