// DO NOT EDIT - auto-generated by alef
// alef:hash:972bff5e8a40a79bf4a9f01e82a7ee1b0a2496d48f1aba85e84510f697b98178
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
