// DO NOT EDIT - auto-generated by alef
// alef:hash:457a1bb6bec3d9f59293ccbd4034b8f6a99c25a99defffc4dcbcee8b4929cf66
package dev.kreuzberg;

public class SerializationException extends KreuzbergErrorException {
    /** Creates a new SerializationException with the given message. */
    public SerializationException(final String message) {
        super(message);
    }

    /** Creates a new SerializationException with the given message and cause. */
    public SerializationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
