// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:73e54541d8b5aa69fe57dd208fa22a60fb1f5b68970fd2cc7779cafec6214699
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;

/**
 * Extracted table from OCR
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
public record Table2(
    List<List<String>> cells,
    String markdown,
    @JsonProperty("page_number") int pageNumber
) {

    /**
     * Parse a {@code Table2} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static Table2 fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, Table2.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse Table2 from JSON: " + e.getMessage(), e);
        }
    }
}
