// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c3cfd99a6f4b803e269aa1ffa92ca5ad90a5af55454795073489bfe5acbc7ac9
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * Column widths from {@code &lt;w:tblGrid&gt;}.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TableTableGrid.Builder.class)
public record TableTableGrid(List<Integer> columns) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code TableTableGrid} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static TableTableGrid fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, TableTableGrid.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse TableTableGrid from JSON: " + e.getMessage(), e);
        }
    }
}
