// DO NOT EDIT - auto-generated by alef
// alef:hash:df38e359f485c5732192c3c6fe89334bbf011b5bd344b7474fab8ad427db8fcb
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
