// DO NOT EDIT - auto-generated by alef
// alef:hash:cbde02ce3bd1408a3c6447bc489e07242272a26afb68a3b790e538da4658792b
package dev.kreuzberg;

public class TimeoutException extends KreuzbergErrorException {
    /** Creates a new TimeoutException with the given message. */
    public TimeoutException(final String message) {
        super(message);
    }

    /** Creates a new TimeoutException with the given message and cause. */
    public TimeoutException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
