// DO NOT EDIT - auto-generated by alef
// alef:hash:2b8dc7fa171be3a5fd6385fcb45f095ad680d2d6b88421494da3d243f11a28d9
package dev.kreuzberg;

public class UnsupportedFormatException extends KreuzbergErrorException {
    /** Creates a new UnsupportedFormatException with the given message. */
    public UnsupportedFormatException(final String message) {
        super(message);
    }

    /** Creates a new UnsupportedFormatException with the given message and cause. */
    public UnsupportedFormatException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
