// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:9d6e44e0362f30e0f175290ba0897d6099eb1e28e837695f238eb6220174540e
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Semantic classification of an extracted URI.
 */
public enum UriKind {
    /** A clickable hyperlink (web URL, file link). */
    Hyperlink("hyperlink"),
    /** An image or media resource reference. */
    Image("image"),
    /** An internal anchor or cross-reference target. */
    Anchor("anchor"),
    /** A citation or bibliographic reference (DOI, academic ref). */
    Citation("citation"),
    /**
     * A general reference (e.g. {@code \ref{}} in LaTeX, {@code :ref:} in RST).
     */
    Reference("reference"),
    /** An email address ({@code mailto:} link or bare email). */
    Email("email");

    /** The string value. */
    private final String value;

    UriKind(final String value) {
        this.value = value;
    }

    /** Returns the string value. */
    @JsonValue
    public String getValue() {
        return value;
    }

    /** Creates an instance from a string value. */
    @JsonCreator
    public static UriKind fromValue(final String value) {
        for (UriKind e : values()) {
            if (e.value.equalsIgnoreCase(value)) {
                return e;
            }
        }
        throw new IllegalArgumentException("Unknown value: " + value);
    }

    /** Returns the wire-format string value (matches JSON serialization). */
    @Override
    public String toString() {
        return value;
    }
}
