// DO NOT EDIT - auto-generated by alef
// alef:hash:29705baee2ba08025b352348e749b712e14e1dcf74471db78bd04d6039e52870
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
