// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:b78e7f22eac6b88e8d68a424c15f0e20dd97fcb5f2f9d3ea21662bc83867a5e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;

/**
 * XML metadata extracted during XML parsing.
 *
 * Provides statistics about XML document structure.
 */
@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = XmlMetadata.Builder.class)
public record XmlMetadata(
    /**
     * Total number of XML elements processed
     */
    @JsonProperty("element_count") int elementCount,
    /**
     * List of unique element tag names (sorted)
     */
    @JsonProperty("unique_elements") List<String> uniqueElements
) {
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Parse a {@code XmlMetadata} from a JSON string.
     *
     * @param json JSON serialisation matching the Rust-side field names (snake_case).
     * @throws KreuzbergRsException if the JSON cannot be deserialised.
     */
    public static XmlMetadata fromJson(String json) throws KreuzbergRsException {
        try {
            return new com.fasterxml.jackson.databind.ObjectMapper()
                .registerModule(new com.fasterxml.jackson.datatype.jdk8.Jdk8Module())
                .findAndRegisterModules()
                .setPropertyNamingStrategy(com.fasterxml.jackson.databind.PropertyNamingStrategies.SNAKE_CASE)
                .setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
                .configure(com.fasterxml.jackson.databind.MapperFeature.ACCEPT_CASE_INSENSITIVE_ENUMS, true)
                .readValue(json, XmlMetadata.class);
        } catch (Exception e) {
            throw new KreuzbergRsException("Failed to parse XmlMetadata from JSON: " + e.getMessage(), e);
        }
    }
}
