// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:ec868084699d51d39b63befc7c127cd0853ae74d674d6fb4963a19d3d011f4b4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * YAKE-specific parameters.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class YakeParamsBuilder {

    @JsonProperty("window_size")
    private long windowSize = 0;

    /** Sets the windowSize field. */
    @JsonProperty("window_size")
    public YakeParamsBuilder withWindowSize(final long value) {
        this.windowSize = value;
        return this;
    }

    /** Builds the YakeParams instance. */
    public YakeParams build() {
        return new YakeParams(
            windowSize
        );
    }
}
