# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:adbcb4c2d9bce683de791429436f63ebb64ad8f9aeaf4fa322461b206bc5024b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AccelerationConfig do
  @moduledoc "Hardware acceleration configuration for ONNX Runtime models."

  defstruct provider: :auto,
            device_id: 0
end
