# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:54b35d1fc82fdf28da39dd57a5815c1c4d278355bcc11540015906c6e5f87a46
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.AnchorProperties do
  @moduledoc "Properties for anchored drawings."

  defstruct behind_doc: false,
            layout_in_cell: false,
            relative_height: 0,
            position_h: "",
            position_v: "",
            wrap_type: ""
end
