# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a12b769ae25f2a9425872e8c5a819b7f21e125fcc1abffa021316c28b48480d6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ApiDoc do
  @moduledoc "OpenAPI documentation structure."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
