# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4ba835df8cae587a5d639c1c7f2f801bbffb95dd42910db1be4f4f8a8966f4ff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc """
  A single file extracted from an archive.

  When archives (ZIP, TAR, 7Z, GZIP) are extracted with recursive extraction
  enabled, each processable file produces its own full `ExtractionResult`.
  """

  @typedoc "A single file extracted from an archive."
  @type t :: %__MODULE__{
          path: String.t() | nil,
          mime_type: String.t() | nil,
          result: map()
        }

  defstruct path: nil,
            mime_type: nil,
            result: nil
end
