# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:278977df342e0b789bd321f05bb7e283787e5b9d5deb82f0e7b899b96791adb9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ArchiveEntry do
  @moduledoc "A single file extracted from an archive."

  defstruct path: "",
            mime_type: "",
            result: nil
end
