# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9373206328de4dd3e8e70d00de534ca8cef888e15b97854628fc37bd80dcd727
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BBox do
  @moduledoc "Bounding box in original image coordinates (x1, y1) top-left, (x2, y2) bottom-right."

  defstruct x1: 0.0,
            y1: 0.0,
            x2: 0.0,
            y2: 0.0
end
