# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:22908a5b7e5b8926af39dc25b6657e8d96484a7e77b18fa33243271cbceb151b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchBytesItem do
  @moduledoc "Batch item for byte array extraction."

  defstruct content: "",
            mime_type: "",
            config: nil
end
