# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9fb1e34c2efeec10c93069aadb57271e70b11ae25b696dedc10041cf32759cbe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BatchFileItem do
  @moduledoc "Batch item for file extraction."

  defstruct path: "",
            config: nil
end
