# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a45afe012023cdb9bf3a16d9bd53f68058dd0c98229b331ac49975b300dce24f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.BibtexMetadata do
  @moduledoc "BibTeX bibliography metadata."

  defstruct entry_count: 0,
            citation_keys: [],
            authors: [],
            year_range: nil,
            entry_types: %{}
end
