# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e81a62129ec66cc1514f3d9da8a4bea2022cadd0bd831f3fc3b10c6253581780
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ByteBufferPool do
  @moduledoc "Convenience type alias for a pooled Vec<u8>."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
