# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ad234ba9394deaa874322e4b08a10cd7defcbb2c8731b7d264cb16643a832c5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CacheWarmParams do
  @moduledoc "Request parameters for cache warm (model download)."

  defstruct all_embeddings: false,
            embedding_model: nil
end
