# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ebe0443611729b40b65bf9dc88049d65383acdc918c492a56d99c7f22da4aea
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CharShape do
  @moduledoc false

  defstruct bold: false,
            italic: false,
            underline: false
end
