# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:65b24752f713a7e6fb2a7d8539f00ec4218df8cc502e5ce5cae780e7a00cf826
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkRequest do
  @moduledoc "Chunk request with text and configuration."

  defstruct text: "",
            config: nil,
            chunker_type: ""
end
