# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bf5f81974217f83d06ee9b668b78bf52882b5594e147b337a313810bc350dd82
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Chunk do
  @moduledoc "A text chunk with optional embedding and metadata."

  defstruct content: "",
            chunk_type: :unknown,
            embedding: nil,
            metadata: nil
end
