# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b020884fe6eef18c22233f93ca9c28e642fe90bc3059c8f47fdcf0f86c194b40
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkResponse do
  @moduledoc "Chunk response with chunks and metadata."

  defstruct chunks: [],
            chunk_count: 0,
            config: "",
            input_size_bytes: 0,
            chunker_type: ""
end
