# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a5f7e618b4d43d6ee6d6631915df60eaccbe537e846fa60dddb4dbe681960e1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkingConfig do
  @moduledoc "Chunking configuration."

  defstruct max_characters: 1_000,
            overlap: 200,
            trim: true,
            chunker_type: :text,
            embedding: nil,
            preset: nil,
            sizing: :characters,
            prepend_heading_context: false,
            topic_threshold: nil
end
