# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9788b6613afaa361d8b67248ea9609d287fd6e3cf276fe7121b1a775e2de6301
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ChunkTextParams do
  @moduledoc "Request parameters for text chunking."

  defstruct text: "",
            max_characters: nil,
            overlap: nil,
            chunker_type: nil,
            topic_threshold: nil
end
