# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f6571b2551f342cf424c2bb0ebe6022617e25a2d363cad3917b6b35aeef2477c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CodeContentMode do
  @moduledoc "Content rendering mode for code extraction."

  @type t :: :chunks | :raw | :structure

  @chunks :chunks
  @raw :raw
  @structure :structure

  @spec chunks() :: t()
  def chunks, do: @chunks
  @spec raw() :: t()
  def raw, do: @raw
  @spec structure() :: t()
  def structure, do: @structure
end
