# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3bbc73fcfa02573ff3bd42f275129a09285c6bfbf483c6946979c0e69fcbb0df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  @typedoc "JATS contributor with role."
  @type t :: %__MODULE__{
          name: String.t() | nil,
          role: String.t() | nil
        }

  defstruct name: nil,
            role: nil
end
