# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:30cbf433e5bccc49172b040fc85f980a5fa06dd590947724787e57c6cbaa032b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContributorRole do
  @moduledoc "JATS contributor with role."

  defstruct name: "",
            role: nil
end
