# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:813702ccd10183fb151afd7be69bd321fa4ed0ba40ffce163d0037b08c5afc03
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentLayer do
  @moduledoc "Content layer classification for document nodes."

  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @spec body() :: t()
  def body, do: @body
  @spec header() :: t()
  def header, do: @header
  @spec footer() :: t()
  def footer, do: @footer
  @spec footnote() :: t()
  def footnote, do: @footnote
end
