# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:783adc76a5c2d2017d6132e1ad7cf144c28aca688c5c95f4a70d672fc5ee7753
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentLayer do
  @moduledoc """
  Content layer classification for document nodes.

  Replaces separate body/furniture arrays with per-node granularity.
  """

  @typedoc "Content layer classification for document nodes."
  @type t :: :body | :header | :footer | :footnote

  @body :body
  @header :header
  @footer :footer
  @footnote :footnote

  @doc "Main document body content."
  @spec body() :: t()
  def body, do: @body
  @doc "Page/section header (running header)."
  @spec header() :: t()
  def header, do: @header
  @doc "Page/section footer (running footer)."
  @spec footer() :: t()
  def footer, do: @footer
  @doc "Footnote content."
  @spec footnote() :: t()
  def footnote, do: @footnote
end
