# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:453c4f93318e6bf04a3e4fe974ed4398c6a3001888ba50f751c58bfa27f0a495
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ContentFilterConfig do
  @moduledoc "Cross-extractor content filtering configuration."

  defstruct include_headers: false,
            include_footers: false,
            strip_repeating_text: true,
            include_watermarks: false
end
