# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bbbd555a3dd272a5ab6f1bde09415cd1aafad34476b723852f509c5552bf7fdf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CoreProperties do
  @moduledoc "Dublin Core metadata from docProps/core.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            keywords: "",
            description: "",
            last_modified_by: "",
            revision: "",
            created: "",
            modified: "",
            category: "",
            content_status: "",
            language: "",
            identifier: "",
            version: "",
            last_printed: ""
end
