# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ea66dce00fc800dc49da68ed4b2c100350b20026609551289235a56651278d2d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CsvMetadata do
  @moduledoc "CSV/TSV file metadata."

  defstruct row_count: 0,
            column_count: 0,
            delimiter: "",
            has_header: false,
            column_types: []
end
