# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0788c89bc81623d4a828a0e5ce2f35a2d449fc73b019e1dd8bc076fe94073471
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.CustomProperties do
  @moduledoc "Custom properties from docProps/custom.xml"

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
