# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3ef6cacea1bda125023a106a4794ef76f8e0e8d814eb8a0cb2e60eadb114041b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
