# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6b07189845c4af24be649b4bf978e0070f4b4965bd7caa9b2eab9383f626dd08
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfMetadata do
  @moduledoc "dBASE (DBF) file metadata."

  @typedoc "dBASE (DBF) file metadata."
  @type t :: %__MODULE__{
          record_count: non_neg_integer(),
          field_count: non_neg_integer(),
          fields: [map()]
        }

  defstruct record_count: 0,
            field_count: 0,
            fields: []
end
