# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c8ff62e07cc57fbfc24b8cbc65f7ffac14e914fc28ef720a5f79f393779d706
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DbfFieldInfo do
  @moduledoc "dBASE field information."

  defstruct name: "",
            field_type: ""
end
