# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4120a713fbfb8617cb70996e326e703652d642b411b7c6132ef26b9c25025b0c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectResponse do
  @moduledoc "MIME type detection response."

  defstruct mime_type: "",
            filename: nil
end
