# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bbf3cc69873049c94d83907e185a942c77b3157b6ce27085f24e4019466235d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectMimeTypeParams do
  @moduledoc "Request parameters for MIME type detection."

  defstruct path: "",
            use_content: false
end
