# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:14eb03757e26f69e925217e737658feeab25166a3367cc68884ffc0da03359bd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DetectedBoundary do
  @moduledoc "A detected structural boundary in the text."

  defstruct byte_offset: 0,
            is_header: false
end
