# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:897f2e5de0209a49c2ecdf5ac62034105643e2d199696b114d7e17ddb9baa9e2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotLink do
  @moduledoc "Link element in Djot."

  defstruct url: "",
            text: "",
            title: nil,
            attributes: nil
end
