# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5035918e687d9a771af6c9f150b9387a0765d7df640574df7f2e09d5c732c73b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc """
  Comprehensive Djot document structure with semantic preservation.

  This type captures the full richness of Djot markup, including:
  - Block-level structures (headings, lists, blockquotes, code blocks, etc.)
  - Inline formatting (emphasis, strong, highlight, subscript, superscript, etc.)
  - Attributes (classes, IDs, key-value pairs)
  - Links, images, footnotes
  - Math expressions (inline and display)
  - Tables with full structure

  Available when the `djot` feature is enabled.
  """

  @typedoc "Comprehensive Djot document structure with semantic preservation."
  @type t :: %__MODULE__{
          plain_text: String.t() | nil,
          blocks: [map()],
          metadata: map(),
          tables: [map()],
          images: [map()],
          links: [map()],
          footnotes: [map()],
          attributes: [String.t()]
        }

  defstruct plain_text: nil,
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
