# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:94d273e63b844b64689b7a89d3d19a85be59b48e1f912b99671d3a129d2bad43
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotContent do
  @moduledoc "Comprehensive Djot document structure with semantic preservation."

  defstruct plain_text: "",
            blocks: [],
            metadata: nil,
            tables: [],
            images: [],
            links: [],
            footnotes: [],
            attributes: []
end
