# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dbce48d098865e3cc80d88b9a3ecd22a717d9b7882a685f3b3a4e948fd94d576
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DjotImage do
  @moduledoc "Image element in Djot."

  defstruct src: "",
            alt: "",
            title: nil,
            attributes: nil
end
