# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bae983aa1b8d50253ba5a89aeb3cdfdfe343bf280ed2ddf62d35eeff38cc7f5e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DoclingCompatResponse do
  @moduledoc "OpenWebUI \"Docling\" engine response format."

  defstruct document: "",
            status: ""
end
