# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:82b87d6b320f3df0b69d02b4c14b4cd776253b0b74d9532c896a9cfdf287e3b7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentRelationship do
  @moduledoc "A resolved relationship between two nodes in the document tree."

  defstruct source: 0,
            target: 0,
            kind: :footnote_reference
end
