# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:048cd759757cf196a2d8fb90360fcbfbeeafbe3c70e13174de36f738fe79a1c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc "A single node in the document tree."

  defstruct id: "",
            content: :title,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
