# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:599c3dc61f9dc804b6f4404d80ada86b5c5c2f7e365a2fcfc9422401c1369c8d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocumentNode do
  @moduledoc """
  A single node in the document tree.

  Each node has deterministic `id`, typed `content`, optional `parent`/`children`
  for tree structure, and metadata like page number, bounding box, and content layer.
  """

  @typedoc "A single node in the document tree."
  @type t :: %__MODULE__{
          id: String.t() | nil,
          content: String.t() | nil,
          parent: non_neg_integer() | nil,
          children: [non_neg_integer()],
          content_layer: String.t() | nil,
          page: non_neg_integer() | nil,
          page_end: non_neg_integer() | nil,
          bbox: String.t() | nil,
          annotations: [map()],
          attributes: map() | nil
        }

  defstruct id: nil,
            content: nil,
            parent: nil,
            children: [],
            content_layer: :body,
            page: nil,
            page_end: nil,
            bbox: nil,
            annotations: [],
            attributes: nil
end
