# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2a962fa184bddc1d6541c868c9370ed9344480df0f9b8df842f9bc7dfc8c9ccb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc "Word document metadata."

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: %{}
end
