# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:040682131a5a324d556d491215a44a84af9e2eaf8f3af3f5acc84012bdcf97a7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for DOCX"

  defstruct application: "",
            app_version: "",
            template: "",
            total_time: 0,
            pages: 0,
            words: 0,
            characters: 0,
            characters_with_spaces: 0,
            lines: 0,
            paragraphs: 0,
            company: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false
end
