# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1dde1c1796215b4635ab6aab694e8166901205b6896c782b9d2b0386a7512f17
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxMetadata do
  @moduledoc """
  Word document metadata.

  Extracted from DOCX files using shared Office Open XML metadata extraction.
  Integrates with `office_metadata` module for core/app/custom properties.
  """

  @typedoc "Word document metadata."
  @type t :: %__MODULE__{
          core_properties: map() | nil,
          app_properties: map() | nil,
          custom_properties: map() | nil
        }

  defstruct core_properties: nil,
            app_properties: nil,
            custom_properties: nil
end
