# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dc2fc7ca883707fc52585483f124341da16a4617b3bbdf594ab4b877159e5edb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DocxAppProperties do
  @moduledoc """
  Application properties from docProps/app.xml for DOCX

  Contains Word-specific document statistics and metadata.
  """

  @typedoc "Application properties from docProps/app.xml for DOCX"
  @type t :: %__MODULE__{
          application: String.t() | nil,
          app_version: String.t() | nil,
          template: String.t() | nil,
          total_time: integer() | nil,
          pages: integer() | nil,
          words: integer() | nil,
          characters: integer() | nil,
          characters_with_spaces: integer() | nil,
          lines: integer() | nil,
          paragraphs: integer() | nil,
          company: String.t() | nil,
          doc_security: integer() | nil,
          scale_crop: boolean() | nil,
          links_up_to_date: boolean() | nil,
          shared_doc: boolean() | nil,
          hyperlinks_changed: boolean() | nil
        }

  defstruct application: nil,
            app_version: nil,
            template: nil,
            total_time: nil,
            pages: nil,
            words: nil,
            characters: nil,
            characters_with_spaces: nil,
            lines: nil,
            paragraphs: nil,
            company: nil,
            doc_security: nil,
            scale_crop: nil,
            links_up_to_date: nil,
            shared_doc: nil,
            hyperlinks_changed: nil
end
