# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5d78b57d3112262d9ceee44d02f4f23185cd9fc2e88a261887db4fde95f0dcef
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.DrawingType do
  @moduledoc "Whether the drawing is inline or anchored."

  @typedoc "Whether the drawing is inline or anchored."
  @type t :: term()

  @type inline :: :inline
  @type anchored :: %{type: :anchored, value: String.t()}
end
