# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ceb7be8bca8bf041b524c0f0a5049369556d32984a6f50bcab986b904a9289e0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Drawing do
  @moduledoc "A drawing object extracted from `<w:drawing>`."

  defstruct drawing_type: "",
            extent: "",
            doc_properties: "",
            image_ref: ""
end
