# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e57af42e6b4658eadf038fe5481fd0929bd39cd0ca875d591fd051db462da2f5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
