# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f548638d58bc3ff023448de12ff68f2b77067120665ed2a71afcad933aaeffd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Element do
  @moduledoc "Semantic element extracted from document."

  defstruct element_id: "",
            element_type: :title,
            text: "",
            metadata: nil
end
