# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:774bd0ae8eb821d83bedc93661224a57e52a94c5b1ea4c59491a669f9dfbf38b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ElementMetadata do
  @moduledoc "Metadata for a semantic element."

  @typedoc "Metadata for a semantic element."
  @type t :: %__MODULE__{
          page_number: non_neg_integer() | nil,
          filename: String.t() | nil,
          coordinates: String.t() | nil,
          element_index: non_neg_integer() | nil,
          additional: map()
        }

  defstruct page_number: nil,
            filename: nil,
            coordinates: nil,
            element_index: nil,
            additional: %{}
end
