# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:340de5949a0ca1108050f85042cca42605db6e1655d9c9fd074e7542af87b84d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailMetadata do
  @moduledoc "Email metadata extracted from .eml and .msg files."

  defstruct from_email: "",
            from_name: "",
            to_emails: [],
            cc_emails: [],
            bcc_emails: [],
            message_id: "",
            attachments: []
end
