# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8fed4b63088a5fb8e09d072cbcd34ee153dc086545d99398193d01ea897a2cff
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailConfig do
  @moduledoc "Configuration for email extraction."

  defstruct msg_fallback_codepage: 0
end
