# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a02cf78ba7662434364cd1e9b128c0dc05abb1c67c35e54e560343794b7c8be1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmailAttachment do
  @moduledoc "Email attachment representation."

  defstruct name: nil,
            filename: nil,
            mime_type: nil,
            size: nil,
            is_image: false,
            data: nil
end
