# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1b244afc546e05314bab3c186cf334c0f30836c106f003363d303ef019e7edce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedRequest do
  @moduledoc "Embedding request for generating embeddings from text."

  defstruct texts: [],
            config: nil
end
