# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0cadec3ddbb70a1f40a97d996e1cc8df0ac7bc27b68bb19bef0de7f3edd5aae1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedResponse do
  @moduledoc "Embedding response containing generated embeddings."

  defstruct embeddings: [],
            model: "",
            dimensions: 0,
            count: 0
end
