# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ba6252aa77c3d96539a0b10c8289a7b4f29a3a0066f6b3f959fc4b89088aa312
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbedTextParams do
  @moduledoc "Request parameters for embedding generation."

  defstruct texts: [],
            preset: nil,
            model: nil,
            api_key: nil,
            embedding_plugin: nil
end
