# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:86ad45613ee438bb56ac44af3c5488cafee543b5422bb9f44696d8d28582452d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingModelType do
  @moduledoc "Embedding model types supported by Kreuzberg."

  @type t :: term()

  @type preset :: %{type: :preset, name: term()}
  @type custom :: %{type: :custom, model_id: term(), dimensions: term()}
  @type llm :: %{type: :llm, llm: term()}
  @type plugin :: %{type: :plugin, name: term()}
end
