# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5c6bd5f979391f0c43689e2aa832ebbafaf7ea931ef7dc766110ccbad0a2b29e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddingPreset do
  @moduledoc "Preset configurations for common RAG use cases."

  defstruct name: "",
            chunk_size: 0,
            overlap: 0,
            model_repo: "",
            pooling: "",
            model_file: "",
            dimensions: 0,
            description: ""
end
