# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4259893db8b06bf0628495bedd6a2c01e1f0c8b19c41aec02e5d7033b7dd4bc9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EmbeddedFile do
  @moduledoc "Embedded file descriptor extracted from the PDF name tree."

  defstruct name: "",
            data: "",
            mime_type: nil
end
