# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:199238cb7010fdcc3d20d003f1cf4744c4f32a14123ac7b7e6881b0260f4ce87
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.EpubMetadata do
  @moduledoc "EPUB metadata (Dublin Core extensions)."

  defstruct coverage: "",
            dc_format: "",
            relation: "",
            source: "",
            dc_type: "",
            cover_image: ""
end
