# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:54225173be1359748930873dad738f5c35fa07e9933a658b003eebdb13a6b886
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ErrorMetadata do
  @moduledoc "Error metadata (for batch operations)."

  defstruct error_type: "",
            message: ""
end
