# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:db36fb9c4a66fdb243088d0b3f8ee7c75a5eb3ad551d922cd1e35ab19043f99d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelMetadata do
  @moduledoc "Excel/spreadsheet format metadata."

  defstruct sheet_count: 0,
            sheet_names: []
end
