# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:15f7d704432c5b0dd13ed60684fffc3eba4d100817254c50595753dff9998f9f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc "Excel workbook representation."

  defstruct sheets: [],
            metadata: %{}
end
