# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:cbc7762783177c93765976a3405e77b29a0325e11760efa35c4c4ab207a27143
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelMetadata do
  @moduledoc """
  Excel/spreadsheet format metadata.

  Identifies the document as a spreadsheet source via the `FormatMetadata::Excel`
  discriminant. Sheet count and sheet names are stored inside this struct.
  """

  @typedoc "Excel/spreadsheet format metadata."
  @type t :: %__MODULE__{
          sheet_count: non_neg_integer() | nil,
          sheet_names: [String.t()] | nil
        }

  defstruct sheet_count: nil,
            sheet_names: nil
end
