# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:02d48f7886e881940e8660a1013a3620d1402d6bd3e1a66641f909bd092de5a6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelWorkbook do
  @moduledoc """
  Excel workbook representation.

  Contains all sheets from an Excel file (.xlsx, .xls, etc.) with
  extracted content and metadata.
  """

  @typedoc "Excel workbook representation."
  @type t :: %__MODULE__{
          sheets: [map()],
          metadata: map()
        }

  defstruct sheets: [],
            metadata: %{}
end
