# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0e84648fb5d615a61697626dd0a108092b5103a998b74bfee54dc2cfa9d3b4ee
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExcelSheet do
  @moduledoc "Single Excel worksheet."

  defstruct name: "",
            markdown: "",
            row_count: 0,
            col_count: 0,
            cell_count: 0,
            table_cells: nil
end
