# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:23866957d5f80a90b258518ba8bfd0f782ccf1f1d90f681550ecbe34f8239886
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExecutionProviderType do
  @moduledoc "ONNX Runtime execution provider type."

  @type t :: :auto | :cpu | :core_ml | :cuda | :tensor_rt

  @auto :auto
  @cpu :cpu
  @core_ml :core_ml
  @cuda :cuda
  @tensor_rt :tensor_rt

  @spec auto() :: t()
  def auto, do: @auto
  @spec cpu() :: t()
  def cpu, do: @cpu
  @spec core_ml() :: t()
  def core_ml, do: @core_ml
  @spec cuda() :: t()
  def cuda, do: @cuda
  @spec tensor_rt() :: t()
  def tensor_rt, do: @tensor_rt
end
