# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:750d79df0095554c1f867be5a2edd1182f6fbdf5b9515ae607c569a9ad9bb3fd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedInlineImage do
  @moduledoc "Extracted inline image with metadata."

  defstruct data: "",
            format: "",
            filename: nil,
            description: nil,
            dimensions: nil,
            attributes: []
end
