# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e3932d049494a00bfd92a874273d2bed0cf4f1e9be846e284be0d8d4da228508
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractionResult2 do
  @moduledoc "OCR extraction result"

  @typedoc "OCR extraction result"
  @type t :: %__MODULE__{
          content: String.t() | nil,
          mime_type: String.t() | nil,
          metadata: map(),
          tables: [map()]
        }

  defstruct content: nil,
            mime_type: nil,
            metadata: %{},
            tables: []
end
