# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a984d7c1ff5d332e082d45f9fd6ac0e5db9b650b80f60e813a0bb0f43f434bd1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractedImageMetadata do
  @moduledoc "Image metadata extracted from an image file."

  @typedoc "Image metadata extracted from an image file."
  @type t :: %__MODULE__{
          width: non_neg_integer(),
          height: non_neg_integer(),
          format: String.t() | nil,
          exif_data: map()
        }

  defstruct width: 0,
            height: 0,
            format: nil,
            exif_data: %{}
end
