# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7b8f332d5294d87290f8d587bff603f9f723f0501f1008371b39fc83fa50c4d9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractResponse do
  @moduledoc "Extraction response (list of results)."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
