# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:78a16e32223944b0d5c56bb5ac0d5b053c979759c4814a1816dcadd7460fcbcf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ExtractStructuredParams do
  @moduledoc "Request parameters for LLM-based structured extraction."

  defstruct path: "",
            schema: "",
            model: "",
            schema_name: "",
            schema_description: nil,
            prompt: nil,
            api_key: nil,
            strict: false
end
