# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c943a1e8e5a6b8d99aa34f2653bd0912748865f8cb2232711b890425c3c874f1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FictionBookMetadata do
  @moduledoc "FictionBook (FB2) metadata."

  defstruct genres: [],
            sequences: [],
            annotation: ""
end
