# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2fc7eb0df6f57a1323c053097e3ce13fa98a6d3e7795f534a1f4ed14623378df
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  defstruct label: "",
            content: []
end
