# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:79e2fb89380372c0bf23c389c5bb7be49b33ed8d8d5483d2696b2702724e4bde
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Footnote do
  @moduledoc "Footnote in Djot."

  @typedoc "Footnote in Djot."
  @type t :: %__MODULE__{
          label: String.t() | nil,
          content: [map()]
        }

  defstruct label: nil,
            content: []
end
