# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5150ed0d50b25a79c9ff0e652907658a15363407d8b81fd97fd2fa8636cdeb77
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc """
  Block-level element in a Djot document.

  Represents structural elements like headings, paragraphs, lists, code blocks, etc.
  """

  @typedoc "Block-level element in a Djot document."
  @type t :: %__MODULE__{
          block_type: String.t() | nil,
          level: non_neg_integer() | nil,
          inline_content: [map()],
          attributes: String.t() | nil,
          language: String.t() | nil,
          code: String.t() | nil,
          children: [map()]
        }

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
