# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f18974ec443f277115f40bce14cd8eead66a3e55353252ced82bdda7afcc9487
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FormattedBlock do
  @moduledoc "Block-level element in a Djot document."

  defstruct block_type: :paragraph,
            level: nil,
            inline_content: [],
            attributes: nil,
            language: nil,
            code: nil,
            children: []
end
