# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4c79bf9ffcf44a99906f9b58eb2a9465230f260d5cce5efaba85b3c7df0edaa4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FracType do
  @moduledoc false

  @type t :: :bar | :no_bar | :linear | :skewed

  @bar :bar
  @no_bar :no_bar
  @linear :linear
  @skewed :skewed

  @spec bar() :: t()
  def bar, do: @bar
  @spec no_bar() :: t()
  def no_bar, do: @no_bar
  @spec linear() :: t()
  def linear, do: @linear
  @spec skewed() :: t()
  def skewed, do: @skewed
end
