# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:307f5a06c03302ee866e446ce8af12a409e105c58912a49c881ffa8208f5cb1c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.FracType do
  @moduledoc false

  @type t :: :bar | :no_bar | :linear | :skewed

  @bar :bar
  @no_bar :no_bar
  @linear :linear
  @skewed :skewed

  @spec bar() :: t()
  def bar, do: @bar
  @spec no_bar() :: t()
  def no_bar, do: @no_bar
  @spec linear() :: t()
  def linear, do: @linear
  @spec skewed() :: t()
  def skewed, do: @skewed
end
