# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b4f6f2df4c773da2aaf8f119fa9bc25fbe92df55db1cd5fb4d203afa0777373c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  defstruct content: "",
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
