# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f8c17dd150c5f4675db86aefc46e86b8475ae16a4e29f75ee73acd0148fa0f9c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.GridCell do
  @moduledoc "Individual grid cell with position and span metadata."

  @typedoc "Individual grid cell with position and span metadata."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row: non_neg_integer(),
          col: non_neg_integer(),
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean(),
          bbox: String.t() | nil
        }

  defstruct content: nil,
            row: 0,
            col: 0,
            row_span: 0,
            col_span: 0,
            is_header: false,
            bbox: nil
end
