# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da58804f6bd7a139f9e74a779160ea11484e1bc93a6e6bddda62320e808b9619
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingLevel do
  @moduledoc "A single heading in the hierarchy."

  defstruct level: 0,
            text: ""
end
