# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6095bad5e603aa45bdd90e1b9df4e4d6c5c0ed0a43d3627e9defc2b01a918a12
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc "Heading context for a chunk within a Markdown document."

  defstruct headings: []
end
