# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:06ff3447ec1011e3ac6d6a440e51c81b8a720ab195a8fcb0ad4e764d0ec6ba33
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  @typedoc "Header/heading element metadata."
  @type t :: %__MODULE__{
          level: non_neg_integer(),
          text: String.t() | nil,
          id: String.t() | nil,
          depth: non_neg_integer(),
          html_offset: non_neg_integer()
        }

  defstruct level: 0,
            text: nil,
            id: nil,
            depth: 0,
            html_offset: 0
end
