# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0d8825ec7d6a095c317994a988d08abbd71f05cc4c84155d3e999281a2283570
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeadingContext do
  @moduledoc """
  Heading context for a chunk within a Markdown document.

  Contains the heading hierarchy from document root to this chunk's section.
  """

  @typedoc "Heading context for a chunk within a Markdown document."
  @type t :: %__MODULE__{
          headings: [map()]
        }

  defstruct headings: []
end
