# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:3b86bc7216175cd09344c88b90f982bdc39d3bc69e1f92ed9cba53a5158009e3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HeaderMetadata do
  @moduledoc "Header/heading element metadata."

  defstruct level: 0,
            text: "",
            id: nil,
            depth: 0,
            html_offset: 0
end
