# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:134dfcc47838fdf33e838344737b7ac9e245ef7845841d080abdb67af6a94e6b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchyConfig do
  @moduledoc "Hierarchy extraction configuration for PDF text structure analysis."

  defstruct enabled: true,
            k_clusters: 3,
            include_bbox: true,
            ocr_coverage_threshold: nil
end
