# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0f72e773976c9e47bbac2543ccd6e9d1d6fa701931fb4df3ef9f50f0960cfcb5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HierarchicalBlock do
  @moduledoc "A text block with hierarchy level assignment."

  defstruct text: "",
            font_size: 0.0,
            level: "",
            bbox: nil
end
