# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:70fe4310e730c105706ba9b83e88ba205a928281d8fd83b70a7c125a8cb58668
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HtmlOutputConfig do
  @moduledoc "Configuration for styled HTML output."

  defstruct css: nil,
            css_file: nil,
            theme: :unstyled,
            class_prefix: "",
            embed_css: true
end
