# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2fdec7a1670c8c0c13f0dc39511034a726138a0d979a5cfd2f000b4a07ad50c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.HwpImage do
  @moduledoc false

  defstruct name: "",
            data: ""
end
