# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:4822db6eecaa4f83f25a1337383eb022fae1634a2103c6e6553e0829863dacd1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  @typedoc "Image element metadata."
  @type t :: %__MODULE__{
          src: String.t() | nil,
          alt: String.t() | nil,
          title: String.t() | nil,
          dimensions: [non_neg_integer()] | nil,
          image_type: String.t() | nil,
          attributes: [String.t()]
        }

  defstruct src: nil,
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
