# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c87861202146c16b04a6034f3e0177a8f613d95ea17012b8bd0cf1f1d8e5e8b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageExtractionConfig do
  @moduledoc "Image extraction configuration."

  @typedoc "Image extraction configuration."
  @type t :: %__MODULE__{
          extract_images: boolean(),
          target_dpi: integer(),
          max_image_dimension: integer(),
          inject_placeholders: boolean(),
          auto_adjust_dpi: boolean(),
          min_dpi: integer(),
          max_dpi: integer(),
          max_images_per_page: non_neg_integer() | nil,
          classify: boolean()
        }

  defstruct extract_images: true,
            target_dpi: 300,
            max_image_dimension: 4_096,
            inject_placeholders: true,
            auto_adjust_dpi: true,
            min_dpi: 72,
            max_dpi: 600,
            max_images_per_page: nil,
            classify: true
end
