# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb2c1b3c17b5462647836723308038c249f3e9d33f9157f685d7ba7a00d295ec
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadata do
  @moduledoc "Image metadata extracted from image files."

  defstruct width: 0,
            height: 0,
            format: "",
            exif: %{}
end
