# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e001e27741c5a7d3ff95f609cb59cf3c7d504285cd7aa9cf02c52ae62ea0faf4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageExtractionConfig do
  @moduledoc "Image extraction configuration."

  defstruct extract_images: true,
            target_dpi: 300,
            max_image_dimension: 4_096,
            inject_placeholders: true,
            auto_adjust_dpi: true,
            min_dpi: 72,
            max_dpi: 600,
            max_images_per_page: nil,
            classify: true
end
