# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6fe5e2dea8e4cda93c3253760340579ee4df05a694143702baf9a04ffdf1911a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImageMetadataType do
  @moduledoc "Image element metadata."

  defstruct src: "",
            alt: nil,
            title: nil,
            dimensions: nil,
            image_type: :data_uri,
            attributes: []
end
