# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:08253bc147ec9640b4b579163c7c9b9d7ccc50a0507614f6b09c3e2f0e03b445
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ImagePreprocessingConfig do
  @moduledoc "Image preprocessing configuration for OCR."

  defstruct target_dpi: 300,
            auto_rotate: true,
            deskew: true,
            denoise: false,
            contrast_enhance: false,
            binarization_method: "otsu",
            invert_colors: false
end
