# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a6d7ac16b67b34f979ec8d87f913df68ddc458c0f0cee7adf41abb7cd7140320
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InfoResponse do
  @moduledoc "Server information response."

  defstruct version: "",
            rust_backend: false
end
