# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:24bb26e15f435c358ad42f92ce4bb8c84ef3d93656089dd74df74649cd39bfe4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.InlineElement do
  @moduledoc """
  Inline element within a block.

  Represents text with formatting, links, images, etc.
  """

  @typedoc "Inline element within a block."
  @type t :: %__MODULE__{
          element_type: String.t() | nil,
          content: String.t() | nil,
          attributes: String.t() | nil,
          metadata: map() | nil
        }

  defstruct element_type: :text,
            content: nil,
            attributes: nil,
            metadata: nil
end
