# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:360a5f6fb3e15853eb36b1ca49160c21aeb5fff02405eeb4656d95d184b51e5e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.JatsMetadata do
  @moduledoc "JATS (Journal Article Tag Suite) metadata."

  defstruct copyright: "",
            license: "",
            history_dates: %{},
            contributor_roles: []
end
