# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a7237f3059c1f7b7cf130e5bb0b8aa39bee1335b13a6c6ca61033ea50a4ef53f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Keyword do
  @moduledoc "Extracted keyword with metadata."

  defstruct text: "",
            score: 0.0,
            algorithm: :yake,
            positions: nil
end
