# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e33db48eb2bb946d57a94cd2ccf1b970ccb3b8b2e4f26f45066c6011268105af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordAlgorithm do
  @moduledoc "Keyword algorithm selection."

  @type t :: :yake | :rake

  @yake :yake
  @rake :rake

  @spec yake() :: t()
  def yake, do: @yake
  @spec rake() :: t()
  def rake, do: @rake
end
