# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:af23d95b91b2922560944bb1d166d9ebf095948d60bbc8f186e55c5b4be4437c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.KeywordConfig do
  @moduledoc "Keyword extraction configuration."

  @typedoc "Keyword extraction configuration."
  @type t :: %__MODULE__{
          algorithm: String.t() | nil,
          max_keywords: non_neg_integer(),
          min_score: float(),
          ngram_range: [non_neg_integer()],
          language: String.t() | nil,
          yake_params: map() | nil,
          rake_params: map() | nil
        }

  defstruct algorithm: :yake,
            max_keywords: 10,
            min_score: 0,
            ngram_range: [],
            language: nil,
            yake_params: nil,
            rake_params: nil
end
