# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0ff567333350f4244d72676d0201683c4cb6ee5f236118047b02407706f752c6
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LanguageDetectionConfig do
  @moduledoc "Language detection configuration."

  defstruct enabled: true,
            min_confidence: 0.8,
            detect_multiple: false
end
