# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:31584fe1c0cbead65aa9337b1aca08e3a38ae0f03bf5bbd3f01abfc24995cff8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutRegion do
  @moduledoc "A detected layout region on a page."

  defstruct class_name: "",
            confidence: 0.0,
            bounding_box: "",
            area_fraction: 0.0
end
