# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:df85961e0b0aaea73eaf906e7b8f2a91fd25372954ca9aa4ac5933040c868825
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  @typedoc "A single layout detection result."
  @type t :: %__MODULE__{
          class_name: String.t() | nil,
          confidence: float(),
          bbox: map()
        }

  defstruct class_name: nil,
            confidence: 0.0,
            bbox: nil
end
