# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:5ee6b481c6788b8ae49525aaa38b2462a13cf9c434dc0238c33e946b90c1e4ca
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetection do
  @moduledoc "A single layout detection result."

  defstruct class_name: :caption,
            confidence: 0.0,
            bbox: nil
end
