# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59a93ca1abf9ddc1a9b3e4feaf8d2e3c1d63eba7a22bf08f0130d7df7461a73a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LayoutDetectionConfig do
  @moduledoc "Layout detection configuration."

  defstruct confidence_threshold: nil,
            apply_heuristics: true,
            table_model: :tatr,
            acceleration: nil
end
