# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d4bb4ae130e96872723df02cfea2e341e5090bd1160c0f75a1e556a83727fa51
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LinkMetadata do
  @moduledoc "Link element metadata."

  defstruct href: "",
            text: "",
            title: nil,
            link_type: :anchor,
            rel: [],
            attributes: []
end
