# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a0788d33a6aed1911f660853a6c847c55157271ddab2b9096d3daa6c1dd94286
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmUsage do
  @moduledoc "Token usage and cost data for a single LLM call made during extraction."

  defstruct model: "",
            source: "",
            input_tokens: 0,
            output_tokens: 0,
            total_tokens: 0,
            estimated_cost: 0.0,
            finish_reason: ""
end
