# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:147a0ec4fd21795931efb1aa17b3107f98665117618ae269dbf3bc0af1df7607
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.LlmConfig do
  @moduledoc "Configuration for an LLM provider/model via liter-llm."

  defstruct model: "",
            api_key: "",
            base_url: "",
            timeout_secs: 0,
            max_retries: 0,
            temperature: 0.0,
            max_tokens: 0
end
