# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0982a8c7b45bfc7a49a43de0b8246e1b4f81e3cb44b0aa93f3db0914535f9cc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ManifestEntryResponse do
  @moduledoc "Model manifest entry for cache management."

  defstruct relative_path: "",
            sha256: "",
            size_bytes: 0,
            source_url: ""
end
