# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7c921f89ed3102d322496cb606e4f80f1b2c9955d736b9e76b18e07763520cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.MergedChunk do
  @moduledoc "A merged chunk produced by [`merge_segments`]."

  defstruct text: "",
            byte_start: 0,
            byte_end: 0
end
