# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d9b5060a5a84c31c8a0b75cce978c915985899a656bf6da5379f1cbf08f39400
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Metadata do
  @moduledoc "Extraction result metadata."

  defstruct title: "",
            subject: "",
            authors: [],
            keywords: [],
            language: "",
            created_at: "",
            modified_at: "",
            created_by: "",
            modified_by: "",
            pages: nil,
            format: :pdf,
            image_preprocessing: nil,
            json_schema: "",
            error: nil,
            extraction_duration_ms: 0,
            category: "",
            tags: [],
            document_version: "",
            abstract_text: "",
            output_format: "",
            ocr_used: false,
            additional: %{}
end
