# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c86584a3e54bf80aa178488aa38a1b23a66a20d2dcefcd3264f05dd12498ee81
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ModelPaths do
  @moduledoc "Combined paths to all models needed for OCR (backward compatibility)."

  defstruct det_model: "",
            cls_model: "",
            rec_model: "",
            dict_file: ""
end
