# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b0e4e44766310e77b0f87be6aed987eb5d1bdfb45f8fe55aa06c2c8bd68ba7a1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineConfig do
  @moduledoc "Multi-backend OCR pipeline with quality-based fallback."

  defstruct stages: [],
            quality_thresholds: nil
end
