# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9377db063252cbc42789e87429d8eba57f8c554313fb48e3c7fc3b3652cae2bb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc "Configuration for OCR element extraction."

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
