# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb4c6ae60ce8e5af583df0c4c1e121a64447eaa8c97b1dfa3a41ca93071f158a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTable do
  @moduledoc "Table detected via OCR."

  defstruct cells: [],
            markdown: "",
            page_number: 0,
            bounding_box: nil
end
