# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e9b0a28bd34ab230d925f776b88fa2c0dedd06f1521b6b03f150845155d6219f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBoundingGeometry do
  @moduledoc "Bounding geometry for an OCR element."

  @type t :: term()

  @type rectangle :: %{type: :rectangle, left: term(), top: term(), width: term(), height: term()}
  @type quadrilateral :: %{type: :quadrilateral, points: term()}
end
