# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7c216f435faffe52b17dd00765ad804c0e8a04bcf73c273b8a8a7f9c09dc1d16
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrBackendType do
  @moduledoc "OCR backend types."

  @type t :: :tesseract | :easy_ocr | :paddle_ocr | :custom

  @tesseract :tesseract
  @easy_ocr :easy_ocr
  @paddle_ocr :paddle_ocr
  @custom :custom

  @spec tesseract() :: t()
  def tesseract, do: @tesseract
  @spec easy_ocr() :: t()
  def easy_ocr, do: @easy_ocr
  @spec paddle_ocr() :: t()
  def paddle_ocr, do: @paddle_ocr
  @spec custom() :: t()
  def custom, do: @custom
end
