# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:33d6c37dbccc100b5c88c08e2d3cd3068bd97061a14b80c4429e81bc0658c9d9
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrTableBoundingBox do
  @moduledoc "Bounding box for an OCR-detected table in pixel coordinates."

  defstruct left: 0,
            top: 0,
            right: 0,
            bottom: 0
end
