# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:9ae3acf139cc78162fdd829d3de3c5658cca4560b61616e0406f6b827bdeddfd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrMetadata do
  @moduledoc "OCR processing metadata."

  defstruct language: "",
            psm: 0,
            output_format: "",
            table_count: 0,
            table_rows: 0,
            table_cols: 0
end
