# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e414ca07156866e07666634f8ecdc8020d7ff896a3575fab6581cfbbaf4206af
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  @type t :: %__MODULE__{
          total_files: non_neg_integer(),
          total_size_mb: float()
        }

  defstruct total_files: 0,
            total_size_mb: 0.0
end
