# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:51b337557ad33d9efeeb3c44295bc413f85596fb0c2efea643e4ebf0b0653090
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElementConfig do
  @moduledoc """
  Configuration for OCR element extraction.

  Controls how OCR elements are extracted and filtered.
  """

  @typedoc "Configuration for OCR element extraction."
  @type t :: %__MODULE__{
          include_elements: boolean(),
          min_level: String.t() | nil,
          min_confidence: float(),
          build_hierarchy: boolean()
        }

  defstruct include_elements: false,
            min_level: :line,
            min_confidence: 0.0,
            build_hierarchy: false
end
