# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd41973e23fb0c8912e5e6cbef3dd9759319780a46eafc362486971b2b023c9b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrElement do
  @moduledoc "A unified OCR element representing detected text with full metadata."

  defstruct text: "",
            geometry: :rectangle,
            confidence: nil,
            level: :line,
            rotation: nil,
            page_number: 0,
            parent_id: "",
            backend_metadata: %{}
end
