# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:722ace49c38cc8ebbbacad1a3107b4796fc51e2ffeb509f4b06836643f44ce08
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc """
  Confidence scores for an OCR element.

  Separates detection confidence (how confident that text exists at this location)
  from recognition confidence (how confident about the actual text content).
  """

  @typedoc "Confidence scores for an OCR element."
  @type t :: %__MODULE__{
          detection: float() | nil,
          recognition: float()
        }

  defstruct detection: nil,
            recognition: 0.0
end
