# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72f502b9a69338cdb4d1ed5db0fa64de6c661e339351d923d6df76ebba1676dc
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrPipelineStage do
  @moduledoc "A single backend stage in the OCR pipeline."

  defstruct backend: "",
            priority: 0,
            language: nil,
            tesseract_config: nil,
            paddle_ocr_config: nil,
            vlm_config: nil,
            backend_options: nil
end
