# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:da025d99907d59c5d27d8ccb42c08bc6eb739fc5842aa226ad604db691132ae7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfidence do
  @moduledoc "Confidence scores for an OCR element."

  defstruct detection: 0.0,
            recognition: 0.0
end
