# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f4b049a086b2a4714133db546af8e123a1ffc8a8c603543ed11109ef55f5de29
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrCacheStats do
  @moduledoc false

  defstruct total_files: 0,
            total_size_mb: 0.0
end
