# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e8ccdcdbdc6dcb9b1b0af0a5f5d6f5b1b593ea1b855d590378e8a8ba1dbd33d2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrConfig do
  @moduledoc "OCR configuration."

  defstruct enabled: true,
            backend: "",
            language: "",
            tesseract_config: nil,
            output_format: nil,
            paddle_ocr_config: nil,
            backend_options: nil,
            element_config: nil,
            quality_thresholds: nil,
            pipeline: nil,
            auto_rotate: false,
            vlm_config: nil,
            vlm_prompt: nil,
            acceleration: nil,
            tessdata_bytes: nil
end
