# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8f1138322c9a47c7c116457d26be94e4febc8c913877a3a1dfd9023bcad1a187
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OcrRotation do
  @moduledoc "Rotation information for an OCR element."

  defstruct angle_degrees: 0.0,
            confidence: nil
end
