# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:869a5429a7d5d2a0e6ca4f9f3a38abc81936de05a952ab9147df8cb4b7fa6099
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OdtProperties do
  @moduledoc "OpenDocument metadata from meta.xml"

  defstruct title: "",
            subject: "",
            creator: "",
            initial_creator: "",
            keywords: "",
            description: "",
            date: "",
            creation_date: "",
            language: "",
            generator: "",
            editing_duration: "",
            editing_cycles: "",
            page_count: 0,
            word_count: 0,
            character_count: 0,
            paragraph_count: 0,
            table_count: 0,
            image_count: 0
end
