# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:49ff7cdb5e7b5c5a44e16b137efb88649ea5b21296601645751bcbf051ac4abe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OpenWebDocumentResponse do
  @moduledoc "OpenWebUI \"External\" engine response format."

  defstruct page_content: "",
            metadata: ""
end
