# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:72b4e8392c31442ca130cd37d0e9c9061e9a38d33d7345737a5569953117f1c1
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.OutputFormat do
  @moduledoc "Output format for extraction results."

  @type t :: term()

  @type plain :: :plain
  @type markdown :: :markdown
  @type djot :: :djot
  @type html :: :html
  @type json :: :json
  @type structured :: :structured
  @type custom :: %{type: :custom, value_0: term()}
end
