# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c820183619a14862c17b2d907216e860543dc300f8ce22cc5720533e265a49b5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageHierarchy do
  @moduledoc "Page hierarchy structure containing heading levels and block information."

  defstruct block_count: 0,
            blocks: []
end
