# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:86afbacf9bf2ad46d01eb6e13524a226cd6dbf4e2d73ad83d1d2528ab7587bfe
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageBoundary do
  @moduledoc "Byte offset boundary for a page."

  defstruct byte_start: 0,
            byte_end: 0,
            page_number: 0
end
