# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:15e5f3640559ec942a6c7c5413df5978e300bd94452e3e02fd1ec86e9a7827e8
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageContent do
  @moduledoc "Content for a single page/slide."

  defstruct page_number: 0,
            content: "",
            tables: [],
            images: [],
            hierarchy: nil,
            is_blank: nil,
            layout_regions: nil
end
