# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f069dfa32a59845be1d6553f9e55c990c75b93e8f495cc1dd2993e015532ffd
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageInfo do
  @moduledoc "Metadata for individual page/slide/sheet."

  defstruct number: 0,
            title: nil,
            dimensions: nil,
            image_count: nil,
            table_count: nil,
            hidden: nil,
            is_blank: nil,
            has_vector_graphics: false
end
