# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ebcd898c5c6c5a8409553be0c4f3dcf157422af1ee0db729c716b390f1d11188
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc """
  Unified page structure for documents.

  Supports different page types (PDF pages, PPTX slides, Excel sheets)
  with character offset boundaries for chunk-to-page mapping.
  """

  @typedoc "Unified page structure for documents."
  @type t :: %__MODULE__{
          total_count: non_neg_integer(),
          unit_type: String.t() | nil,
          boundaries: [map()] | nil,
          pages: [map()] | nil
        }

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
