# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7fda690a80e9136e9b28595afb2e4ab8c9ed76530ffc5f4dfce7da234df32b61
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageStructure do
  @moduledoc "Unified page structure for documents."

  defstruct total_count: 0,
            unit_type: :page,
            boundaries: nil,
            pages: nil
end
