# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:48697683a021b9c362a56d240ab9621f7d78357949e1df143262ea2a4fb151c2
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageConfig do
  @moduledoc "Page extraction and tracking configuration."

  defstruct extract_pages: false,
            insert_page_markers: false,
            marker_format: "

<!-- PAGE {page_num} -->

"
end
