# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:15251905ad238fb6df8affeb447945ec82799b8d921650440a4f79d8bf9789cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PageMarginsPoints do
  @moduledoc "Page margins converted to points (1/72 inch)."

  defstruct top: 0.0,
            right: 0.0,
            bottom: 0.0,
            left: 0.0,
            header: 0.0,
            footer: 0.0,
            gutter: 0.0
end
