# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c7a254ca82c32469ddaa64ade26ad0759a349b12a2a62cecdfa6ad093e682c56
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfMetadata do
  @moduledoc "PDF-specific metadata."

  defstruct pdf_version: "",
            producer: "",
            is_encrypted: false,
            width: 0,
            height: 0,
            page_count: 0
end
