# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:6f1d286204f89476bd711afa17f6a6f30e3940c8cd74cf32fa1a27e913a4ea8f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PdfAnnotation do
  @moduledoc "A PDF annotation extracted from a document page."

  defstruct annotation_type: :text,
            content: nil,
            page_number: 0,
            bounding_box: nil
end
