# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7975b1b406169810aca4ee567c691d6a5dc34dc628d9b602fa007cd5505f862e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PoolError do
  @moduledoc "Error type for pool operations."

  @type t :: :lock_poisoned

  @lock_poisoned :lock_poisoned

  @spec lock_poisoned() :: t()
  def lock_poisoned, do: @lock_poisoned
end
