# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:974ca8fd8cffcae41a7e8809745ab709b81c87cfc2d6d215ed028adadc07d4e7
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
