# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:82de339feb59639bf31d5e5eee4131fdf11bab3edd9ac6dd88b95e0773e4b873
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PostProcessorConfig do
  @moduledoc "Post-processor configuration."

  @typedoc "Post-processor configuration."
  @type t :: %__MODULE__{
          enabled: boolean(),
          enabled_processors: [String.t()] | nil,
          disabled_processors: [String.t()] | nil,
          enabled_set: [String.t()] | nil,
          disabled_set: [String.t()] | nil
        }

  defstruct enabled: true,
            enabled_processors: nil,
            disabled_processors: nil,
            enabled_set: nil,
            disabled_set: nil
end
