# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8c2f72a01094c2aecf9c3ba12b3df48b6ec02fe1ead4355e76f549b30079910
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc "PowerPoint presentation metadata."

  defstruct slide_count: 0,
            slide_names: [],
            image_count: 0,
            table_count: 0
end
