# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:73b04de6c12d524cdd8145135f448f1edbad1c29bbb588684a089ba284d7da1b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PptxMetadata do
  @moduledoc """
  PowerPoint presentation metadata.

  Extracted from PPTX files containing slide counts and presentation details.
  """

  @typedoc "PowerPoint presentation metadata."
  @type t :: %__MODULE__{
          slide_count: non_neg_integer(),
          slide_names: [String.t()],
          image_count: non_neg_integer() | nil,
          table_count: non_neg_integer() | nil
        }

  defstruct slide_count: 0,
            slide_names: [],
            image_count: nil,
            table_count: nil
end
