# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d45cb592e8a36eb752878783a6aef4c01f1b554bfeadd912187753f0881bb566
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingStage do
  @moduledoc "Processing stages for post-processors."

  @type t :: :early | :middle | :late

  @early :early
  @middle :middle
  @late :late

  @spec early() :: t()
  def early, do: @early
  @spec middle() :: t()
  def middle, do: @middle
  @spec late() :: t()
  def late, do: @late
end
