# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:53027eccc3b2dc780fbd34dd74e9d148d9ce3908fd02ea8c967d70895541fe9d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ProcessingWarning do
  @moduledoc "A non-fatal warning from a processing pipeline stage."

  defstruct source: "",
            message: ""
end
