# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:d0f89ddff3ac30cba0e9c244320403cf453458cab292be92977d3414817d8931
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  @typedoc "Outlook PST archive metadata."
  @type t :: %__MODULE__{
          message_count: non_neg_integer()
        }

  defstruct message_count: 0
end
