# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f196efa0e27529925f821fd9423a3c47b25e894ef330424516dde8657c338c27
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.PstMetadata do
  @moduledoc "Outlook PST archive metadata."

  defstruct message_count: 0
end
