# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f93ab04e7b7f3efa68024efd5e54f097ad9bb7f357b4919625c9fa3317069c48
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RakeParams do
  @moduledoc "RAKE-specific parameters."

  @typedoc "RAKE-specific parameters."
  @type t :: %__MODULE__{
          min_word_length: non_neg_integer(),
          max_words_per_phrase: non_neg_integer()
        }

  defstruct min_word_length: 1,
            max_words_per_phrase: 3
end
