# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e51ea2aae593d8390e66328553f1be4d6280bd859eee125b8719c2f9b28da42
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.RecognizedTable do
  @moduledoc "Pre-computed table markdown for a table detection region."

  defstruct detection_bbox: nil,
            cells: [],
            markdown: ""
end
