# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a8554d4ac9c718df5e01c579cf5f4bfb482553d1dd555968d80a676d0437b403
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ResolvedStyle do
  @moduledoc "Fully resolved (flattened) style after walking the inheritance chain."

  defstruct paragraph_properties: "",
            run_properties: ""
end
