# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:85afce24bd62a7d13c27f60215448657c3d1f503658213316732a91e8c21f3cf
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ServerConfig do
  @moduledoc "API server configuration."

  defstruct host: "",
            port: 0,
            cors_origins: [],
            max_request_body_bytes: 0,
            max_multipart_field_bytes: 0
end
