# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:409519e24227f4d4c024f54498d77ee922b7f34fff67e314b908445f2984be72
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StreamReader do
  @moduledoc false

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
