# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:bb8dfe2c926041d786dc58d33b340cca20a5c561a2635f54c618a7ea99df7501
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StringBufferPool do
  @moduledoc "Convenience type alias for a pooled String."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
