# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c9e86e80e7fa76b93e247f594a3ef894e95f07f4d06b99281f1f9e7b223b695c
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredDataType do
  @moduledoc "Structured data type classification."

  @type t :: :json_ld | :microdata | :rd_fa

  @json_ld :json_ld
  @microdata :microdata
  @rd_fa :rd_fa

  @spec json_ld() :: t()
  def json_ld, do: @json_ld
  @spec microdata() :: t()
  def microdata, do: @microdata
  @spec rd_fa() :: t()
  def rd_fa, do: @rd_fa
end
