# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8eb3b28cbda1ab442e75fbf030a2bc1acf0268dfdf4460710fd90ee18bcaae7a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionConfig do
  @moduledoc "Configuration for LLM-based structured data extraction."

  defstruct schema: "",
            schema_name: "",
            schema_description: nil,
            strict: false,
            prompt: nil,
            llm: nil
end
