# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f54ee1aaa96d7a37ef2b807992621376d70a4e8faf899751872eded49f51a442
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredExtractionResponse do
  @moduledoc "Response from structured extraction endpoint."

  defstruct structured_output: "",
            content: "",
            mime_type: ""
end
