# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ffb499836141a144a3ed74c2c940300d78e29370fd4c1f2c5a7695e1e7c6516d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  @typedoc "Structured data (Schema.org, microdata, RDFa) block."
  @type t :: %__MODULE__{
          data_type: String.t() | nil,
          raw_json: String.t() | nil,
          schema_type: String.t() | nil
        }

  defstruct data_type: :json_ld,
            raw_json: nil,
            schema_type: nil
end
