# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:59ecedc8d1dc24aec2f579cbcc57304b91fba5214bc1463aeff92aae67245596
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StructuredData do
  @moduledoc "Structured data (Schema.org, microdata, RDFa) block."

  defstruct data_type: :json_ld,
            raw_json: "",
            schema_type: nil
end
