# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:172ac84936a4f5645d9003735516c10c04184381c0eb3a3348f27cd461654f52
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.StyleDefinition do
  @moduledoc "A single style definition parsed from `<w:style>` in `word/styles.xml`."

  defstruct id: "",
            name: nil,
            style_type: "",
            based_on: nil,
            next_style: nil,
            is_default: false,
            paragraph_properties: "",
            run_properties: ""
end
