# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:67762d18aca29943b9f5e2c8009205fed36023fbc6c94c551e1a327f58eb443f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc "A supported document format entry."

  defstruct extension: "",
            mime_type: ""
end
