# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1ca481852b01d0314b7ddee1dc68f911fc3260188b09623daf3e41bc7b84bd4f
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.SupportedFormat do
  @moduledoc """
  A supported document format entry.

  Represents a file extension and its corresponding MIME type that Kreuzberg can process.
  """

  @typedoc "A supported document format entry."
  @type t :: %__MODULE__{
          extension: String.t() | nil,
          mime_type: String.t() | nil
        }

  defstruct extension: nil,
            mime_type: nil
end
