# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:ca5f7da1682e07b9e83fbae0aa7f18b893fdb23541d06312c0ddbcd7fc7816e5
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc """
  Individual table cell with content and optional styling.

  Future extension point for rich table support with cell-level metadata.
  """

  @typedoc "Individual table cell with content and optional styling."
  @type t :: %__MODULE__{
          content: String.t() | nil,
          row_span: non_neg_integer(),
          col_span: non_neg_integer(),
          is_header: boolean()
        }

  defstruct content: nil,
            row_span: 0,
            col_span: 0,
            is_header: false
end
