# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f1b790594780fa3f2e79fc33231eb3c21f68186dc44673582e49c740ed968587
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableGrid do
  @moduledoc "Structured table grid with cell-level metadata."

  defstruct rows: 0,
            cols: 0,
            cells: []
end
