# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0b35e6d5d53ae8940b420cacccb7a3160063e4f7cf2fb23d37441afa91eaaf8a
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableCell do
  @moduledoc "Individual table cell with content and optional styling."

  defstruct content: "",
            row_span: 0,
            col_span: 0,
            is_header: false
end
