# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1583ff5b43f69d3a896e1d7a21887f663a7a7b0e594294ad06b6785b927c259
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableProperties do
  @moduledoc "Table-level properties from `<w:tblPr>`."

  defstruct style_id: "",
            width: "",
            alignment: "",
            layout: "",
            look: "",
            borders: "",
            cell_margins: "",
            indent: "",
            caption: ""
end
