# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7cd71aacacbf9257ff6c2a345fda34dab180261ac42a2644d85f039fc0f88293
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Table2 do
  @moduledoc "Extracted table from OCR"

  @typedoc "Extracted table from OCR"
  @type t :: %__MODULE__{
          cells: [[String.t()]],
          markdown: String.t() | nil,
          page_number: integer()
        }

  defstruct cells: [],
            markdown: nil,
            page_number: 0
end
