# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:a380bb37342a4e7012dd49fb2fa6e694a502e94d80e3400dc30214ce71a51c10
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TableTableGrid do
  @moduledoc "Column widths from `<w:tblGrid>`."

  @typedoc "Column widths from `<w:tblGrid>`."
  @type t :: %__MODULE__{
          columns: [integer()]
        }

  defstruct columns: []
end
