# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:1321e0a265420f86ca2bdf8714f61a6e29c33c3ddc45cf5c4b8fb821c3d65555
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc """
  Text/Markdown metadata.

  Extracted from plain text and Markdown files. Includes word counts and,
  for Markdown, structural elements like headers and links.
  """

  @typedoc "Text/Markdown metadata."
  @type t :: %__MODULE__{
          line_count: non_neg_integer(),
          word_count: non_neg_integer(),
          character_count: non_neg_integer(),
          headers: [String.t()] | nil,
          links: [String.t()] | nil,
          code_blocks: [String.t()] | nil
        }

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: nil,
            links: nil,
            code_blocks: nil
end
