# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:17b049852a981d5e892af7a45abaad99ad1deaf3eff968729fddc616841c3959
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextAnnotation do
  @moduledoc "Inline text annotation — byte-range based formatting and links."

  defstruct start: 0,
            end: 0,
            kind: :bold
end
