# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b27d543be5f786daad0e3a62eaea7ba0aae9ee4a2a4455a7e6ef9100585c57a0
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TextMetadata do
  @moduledoc "Text/Markdown metadata."

  defstruct line_count: 0,
            word_count: 0,
            character_count: 0,
            headers: [],
            links: [],
            code_blocks: []
end
