# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:61ba1a2322acc065ce2a228d07d25e48dd1e3fb96d2b65ca835cb10eeac4b083
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionOptions do
  @moduledoc "Token reduction configuration."

  defstruct mode: "",
            preserve_important_words: true
end
