# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:8e53e52a7ee3d303af3fb3a5b499239071906d198095177f18b2a516294c2cc3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TokenReductionConfig do
  @moduledoc false

  defstruct level: :moderate,
            language_hint: nil,
            preserve_markdown: false,
            preserve_code: true,
            semantic_threshold: 0.3,
            enable_parallel: true,
            use_simd: true,
            custom_stopwords: nil,
            preserve_patterns: [],
            target_reduction: nil,
            enable_semantic_clustering: false
end
