# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:fb0c490f4e52cfdf29ef753ba8de4a6683ae33ca1f3e1b77361e6917c14f4313
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TracingLayer do
  @moduledoc "A [`tower::Layer`] that wraps each extraction in a semantic tracing span."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}

  @doc "Build a default instance."
  @spec new() :: t()
  def new do
    %__MODULE__{ref: Native.tracinglayer_default()}
  end
end
