# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0377a9fd61369e27f7b4ba5246eefffcc7a204f46ef1bf1349dd5c6143e1041e
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.TreeSitterConfig do
  @moduledoc "Configuration for tree-sitter language pack integration."

  defstruct enabled: true,
            cache_dir: nil,
            languages: nil,
            groups: nil,
            process: nil
end
