# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:2e10b6604b143c5298f7432091d2cd4900e85ab11fb2399406cd82af2466fe71
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.Uri do
  @moduledoc "A URI extracted from a document."

  defstruct url: "",
            label: nil,
            page: nil,
            kind: :hyperlink
end
