# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:81fff2cbb06535ba1a54dd90759c75f90f9e49f17e5aa896b974d77616e37075
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.WarmResponse do
  @moduledoc "Cache warm response."

  defstruct cache_dir: "",
            downloaded: [],
            already_cached: []
end
