# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:16e3e4eb07ad15f958923df9fe90a37c7a57fa4fb5ab1f0a5ee1434b1b82180d
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XlsxAppProperties do
  @moduledoc "Application properties from docProps/app.xml for XLSX"

  defstruct application: "",
            app_version: "",
            doc_security: 0,
            scale_crop: false,
            links_up_to_date: false,
            shared_doc: false,
            hyperlinks_changed: false,
            company: "",
            worksheet_names: []
end
