# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:19f89c26b7bfff3919324c1cbcb0d9eec154ea39bc8b354a6f9779b4b6f4d08b
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.XmlMetadata do
  @moduledoc "XML metadata extracted during XML parsing."

  defstruct element_count: 0,
            unique_elements: []
end
