# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:c1a504710e51294c71c5fd601d296b5725f948518215290ca0a4e8d29750bc15
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  defstruct window_size: 2
end
