# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:e902b88be1f039cb456eaabbc0ef4bb53f3af716f62a682371055e7614c58849
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YakeParams do
  @moduledoc "YAKE-specific parameters."

  @typedoc "YAKE-specific parameters."
  @type t :: %__MODULE__{
          window_size: non_neg_integer()
        }

  defstruct window_size: 2
end
