# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:7a7937fd2a878b48790111d83aa0fc8360c21fcf007b6d258aa8a61b670391d4
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  defstruct min: nil,
            max: nil,
            years: []
end
