# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:0113370973e368e49f55d2c58dd1609add08c58c5f3df56014801d89dad7ffce
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.YearRange do
  @moduledoc "Year range for bibliographic metadata."

  @typedoc "Year range for bibliographic metadata."
  @type t :: %__MODULE__{
          min: non_neg_integer() | nil,
          max: non_neg_integer() | nil,
          years: [non_neg_integer()]
        }

  defstruct min: nil,
            max: nil,
            years: []
end
