# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:dd5d54ed91d6e06edc91d1b00f3b86eb55b41a5bdf376ae6af0ef8f74c364ffb
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef
defmodule Kreuzberg.ZipBombValidator do
  @moduledoc "Helper struct for validating ZIP archives for security issues."

  alias Kreuzberg.Native

  defstruct [:ref]

  @type t :: %__MODULE__{ref: reference()}
end
