// DO NOT EDIT - auto-generated by alef
// alef:hash:322c77a28f49904c7f64095d3db6835c929f8f6556b5d989539d7c8f733ce17b
package dev.kreuzberg;

public class CancelledException extends KreuzbergErrorException {
    /** Creates a new CancelledException with the given message. */
    public CancelledException(final String message) {
        super(message);
    }

    /** Creates a new CancelledException with the given message and cause. */
    public CancelledException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
