// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:c0323b8e807bc203848b9abd97ebbb7ef0acd410c6f0854d6a297e72213bd0de
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.util.Optional;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Configuration for email extraction.
 */
@JsonPOJOBuilder(withPrefix = "with")
public class EmailConfigBuilder {

    @JsonProperty("msg_fallback_codepage")
    private Optional<Integer> msgFallbackCodepage = Optional.empty();

    /** Sets the msgFallbackCodepage field. */
    @JsonProperty("msg_fallback_codepage")
    public EmailConfigBuilder withMsgFallbackCodepage(final Optional<Integer> value) {
        this.msgFallbackCodepage = value;
        return this;
    }

    /** Builds the EmailConfig instance. */
    public EmailConfig build() {
        return new EmailConfig(
            msgFallbackCodepage.orElse(null)
        );
    }
}
