// DO NOT EDIT - auto-generated by alef
// alef:hash:29a6b683b243500df01bacdaf9472bfe52ee6ca94355a54ba7e2a30a63d87caf
package dev.kreuzberg;

public class EmbeddingException extends KreuzbergErrorException {
    /** Creates a new EmbeddingException with the given message. */
    public EmbeddingException(final String message) {
        super(message);
    }

    /** Creates a new EmbeddingException with the given message and cause. */
    public EmbeddingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
