// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:4be48e196c8564e79b5aebd70839aa65642ce6dc7e48ddc606781efdaa53e1e4
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonPOJOBuilder(withPrefix = "with")
public class HwpImageBuilder {

    @JsonProperty("name")
    private String name = "";
    @JsonProperty("data")
    private byte[] data = new byte[0];

    /** Sets the name field. */
    @JsonProperty("name")
    public HwpImageBuilder withName(final String value) {
        this.name = value;
        return this;
    }

    /** Sets the data field. */
    @JsonProperty("data")
    public HwpImageBuilder withData(final byte[] value) {
        this.data = value;
        return this;
    }

    /** Builds the HwpImage instance. */
    public HwpImage build() {
        return new HwpImage(
            name,
            data
        );
    }
}
