// DO NOT EDIT - auto-generated by alef
// alef:hash:391031d6a253f41963e2752dd249c64dc49f390d8a8ae52ae30edea5dc27aed3
package dev.kreuzberg;

public class ImageProcessingException extends KreuzbergErrorException {
    /** Creates a new ImageProcessingException with the given message. */
    public ImageProcessingException(final String message) {
        super(message);
    }

    /** Creates a new ImageProcessingException with the given message and cause. */
    public ImageProcessingException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
