// DO NOT EDIT - auto-generated by alef
// alef:hash:3dcda54d257def7719e678221faa02d721e5ab104968826e89c0f124e3eaed11
package dev.kreuzberg;

public class LockPoisonedException extends KreuzbergErrorException {
    /** Creates a new LockPoisonedException with the given message. */
    public LockPoisonedException(final String message) {
        super(message);
    }

    /** Creates a new LockPoisonedException with the given message and cause. */
    public LockPoisonedException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
