// DO NOT EDIT - auto-generated by alef
// alef:hash:3889ad24e7a7604008b6cf1317f355f673c5134ffb21cf66d18de293aac74956
package dev.kreuzberg;

public class MissingDependencyException extends KreuzbergErrorException {
    /** Creates a new MissingDependencyException with the given message. */
    public MissingDependencyException(final String message) {
        super(message);
    }

    /** Creates a new MissingDependencyException with the given message and cause. */
    public MissingDependencyException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
