// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:566f6b7346160566b0cb4d636857e7d3d6b9e41b278009fcc7bc0810503a2a52
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonPOJOBuilder(withPrefix = "with")
public class OcrCacheStatsBuilder {

    @JsonProperty("total_files")
    private long totalFiles = 0;
    @JsonProperty("total_size_mb")
    private double totalSizeMb = 0.0;

    /** Sets the totalFiles field. */
    @JsonProperty("total_files")
    public OcrCacheStatsBuilder withTotalFiles(final long value) {
        this.totalFiles = value;
        return this;
    }

    /** Sets the totalSizeMb field. */
    @JsonProperty("total_size_mb")
    public OcrCacheStatsBuilder withTotalSizeMb(final double value) {
        this.totalSizeMb = value;
        return this;
    }

    /** Builds the OcrCacheStats instance. */
    public OcrCacheStats build() {
        return new OcrCacheStats(
            totalFiles,
            totalSizeMb
        );
    }
}
