// DO NOT EDIT - auto-generated by alef
// alef:hash:537def6a43a2b27018802b7fd3ec25f0918fb98d84b7935cbea38657dd7c915d
package dev.kreuzberg;

public class OcrException extends KreuzbergErrorException {
    /** Creates a new OcrException with the given message. */
    public OcrException(final String message) {
        super(message);
    }

    /** Creates a new OcrException with the given message and cause. */
    public OcrException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
