// DO NOT EDIT - auto-generated by alef
// alef:hash:815f01280ec4feac96c699056acbe52a842092f7569384a77417ec2721a16f0f
package dev.kreuzberg;

public class SecurityException extends KreuzbergErrorException {
    /** Creates a new SecurityException with the given message. */
    public SecurityException(final String message) {
        super(message);
    }

    /** Creates a new SecurityException with the given message and cause. */
    public SecurityException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
