// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:3d16faa4de5411bf2825ee9e9d872e9de50786c2ebf70fbc22c16199447631e0
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
package dev.kreuzberg;

import java.lang.foreign.MemorySegment;

/**
 * A tower::Layer that wraps each extraction in a semantic tracing span.
 */
public class TracingLayer implements AutoCloseable {
    private final MemorySegment handle;

    TracingLayer(MemorySegment handle) {
        this.handle = handle;
    }

    MemorySegment handle() {
        return this.handle;
    }

    @Override
    public void close() {
        if (handle != null && !handle.equals(MemorySegment.NULL)) {
            try {
                NativeLib.KREUZBERG_TRACING_LAYER_FREE.invoke(handle);
            } catch (Throwable e) {
                throw new RuntimeException("Failed to free TracingLayer: " + e.getMessage(), e);
            }
        }
    }
}
