// DO NOT EDIT - auto-generated by alef
// alef:hash:bfea0b4fd5414436a1dcf7a063d68b3d6f22efd4626e71366c28f1079fedec4b
package dev.kreuzberg;

public class ValidationException extends KreuzbergErrorException {
    /** Creates a new ValidationException with the given message. */
    public ValidationException(final String message) {
        super(message);
    }

    /** Creates a new ValidationException with the given message and cause. */
    public ValidationException(final String message, final Throwable cause) {
        super(message, cause);
    }
}
