# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:80a26e6e4c3564c39f349eef929a8c8d9076cc5f791c92d4f9bf1e08d15e23d3
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
