# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:f05401cf6bd15fea948b929ecb9826e21b2e00fe1fc2222bdcc8c6debdbd8263
# To regenerate: alef generate
# To verify freshness: alef verify --exit-code
# Issues & docs: https://github.com/kreuzberg-dev/alef

#' @useDynLib kreuzberg, .registration = TRUE
NULL
