// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:886c225bd4e0f96ed77590ab2de8b67bb60febb1ee5306f40cc02576b59462ed
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
// ignore_for_file: unused_local_variable

import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:convert';

// E2e tests for category: batch
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('Extract text from multiple files asynchronously', () async {
    final result = await KreuzbergBridge.batchExtractFiles([BatchFileItem(path: 'pdf/fake_memo.pdf'), BatchFileItem(path: 'text/fake_text.txt')]);
  });

  test('batch_extract_file async nonexistent', () async {
    final result = await KreuzbergBridge.batchExtractFiles([BatchFileItem(path: '/nonexistent/a.pdf')]);
  });

  test('batch_extract_file_sync nonexistent', () async {
    final result = await KreuzbergBridge.batchExtractFilesSync([BatchFileItem(path: '/nonexistent/a.pdf'), BatchFileItem(path: '/nonexistent/b.txt')]);
  });

  test('batch_extract_file_sync mixed', () async {
    final result = await KreuzbergBridge.batchExtractFilesSync([BatchFileItem(path: 'text/plain.txt'), BatchFileItem(path: '/nonexistent/missing.pdf')]);
  });

  test('Extract text from multiple files synchronously', () async {
    final result = await KreuzbergBridge.batchExtractFilesSync([BatchFileItem(path: 'pdf/fake_memo.pdf'), BatchFileItem(path: 'text/fake_text.txt')]);
  });

}
