// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:18aca69c53424e027feaa201fd01f6130a89a404c711bf3f23dae7843a2f5d50
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;
import 'dart:convert';

// E2e tests for category: embeddings
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('embed_texts: multilingual preset', () async {
    final _config = await createEmbeddingConfigFromJson(json: '{"model":{"name":"multilingual","type":"preset"}}');
    final result = await KreuzbergBridge.embedTexts(<String>['Hello world', 'Test'], _config);
    expect(result.length, greaterThanOrEqualTo(2));
  });

  test('get_embedding_preset: known preset', () async {
    final result = await KreuzbergBridge.getEmbeddingPreset('balanced');
  });

  test('get_embedding_preset: nominal case', () async {
    final result = await KreuzbergBridge.getEmbeddingPreset('balanced');
  });

  test('get_embedding_preset: unknown preset fails', () async {
    final result = await KreuzbergBridge.getEmbeddingPreset('nonexistent-xyz');
    expect(result, anyOf(isNull, isEmpty));
  });

  test('list_embedding_presets: returns at least one', () async {
    final result = await KreuzbergBridge.listEmbeddingPresets();
    expect(result, isNotNull);
  });

}
