// This file is auto-generated by alef — DO NOT EDIT.
// alef:hash:dc9c4928e5926ed3adb3b6187ea063d57a626b6f1644dc14898aa603534a8a98
// To regenerate: alef generate
// To verify freshness: alef verify --exit-code
// Issues & docs: https://github.com/kreuzberg-dev/alef
import 'package:test/test.dart';
import 'package:kreuzberg/kreuzberg.dart';
import 'package:kreuzberg/src/kreuzberg_bridge_generated/frb_generated.dart' show RustLib;

// E2e tests for category: registry
void main() {
  setUpAll(() async {
    await RustLib.init();
  });

  test('List document extractors', () async {
    final result = await KreuzbergBridge.listDocumentExtractors();
  });

  test('List embedding backends', () async {
    final result = await KreuzbergBridge.listEmbeddingBackends();
  });

  test('List OCR backends', () async {
    final result = await KreuzbergBridge.listOcrBackends();
  });

  test('List post-processors', () async {
    final result = await KreuzbergBridge.listPostProcessors();
  });

  test('List renderers', () async {
    final result = await KreuzbergBridge.listRenderers();
  });

  test('List validators', () async {
    final result = await KreuzbergBridge.listValidators();
  });

}
